apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: default
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: gen3-infrastructure
