# Pod Identity configuration for ACK CLOUDWATCHLOGS controller
# Base values - can be overridden by tenant/environment/cluster specific values

podIdentityRole:
  description: "Pod Identity Role for ACK CLOUDWATCHLOGS Controller"
  managedPolicies: []
  policyRefs: []

podIdentityPolicy:
  description: "IAM Policy for ACK CLOUDWATCHLOGS Controller"
  policies: []
