apiVersion: kro.run/v1alpha1
kind: AwsGenericCommonsAndBucket
metadata:
  name: awsgenericcommonsandbucket
  namespace: spoke1-infrastructure
spec:
  name: my-gen3-commons
  namespace: spoke1-infrastructure
  region: us-east-1
  environment: dev
  project: Gen3

  # Feature Toggles - control which resources are deployed
  features:
    enableEKS: true
    enableAurora: true
    enableElastiCache: false
    enableEFS: false
    enableKMS: false
    enableOpenSearch: false
    enableCloudWatchLogs: false
    enableCloudTrail: false
    enableDataBucket: false
    enableLoggingBucket: false
    enableUploadBucket: false

  # VPC Configuration
  vpc:
    features:
      enableSubnet2: true
      enableSubnet3: false
      enableDbSubnet2: true
    cidr:
      vpcCidr: "10.1.0.0/16"
      publicSubnet1Cidr: "10.1.1.0/24"
      publicSubnet2Cidr: "10.1.2.0/24"
      publicSubnet3Cidr: "10.1.3.0/24"
      privateSubnet1Cidr: "10.1.11.0/24"
      privateSubnet2Cidr: "10.1.12.0/24"
      privateSubnet3Cidr: "10.1.13.0/24"
      dbSubnet1Cidr: "10.1.21.0/24"
      dbSubnet2Cidr: "10.1.22.0/24"

  # EKS Configuration
  eks:
    version: "1.33"
    nodeGroupInstanceTypes:
      - "t3.large"
    nodeGroupDesiredSize: 3
    nodeGroupMinSize: 2
    nodeGroupMaxSize: 6

  # Aurora PostgreSQL Configuration
  aurora:
    engine: "aurora-postgresql"
    engineVersion: "15.13"
    instanceClass: "db.r5.large"
    instanceCount: 2
    databaseName: "gen3"
    masterUsername: "gen3admin"
    backupRetentionPeriod: 7

  # ElastiCache Configuration
  elasticache:
    engine: "redis"
    engineVersion: "7.0"
    nodeType: "cache.t3.micro"
    numCacheNodes: 1

  # EFS Configuration
  efs:
    performanceMode: "generalPurpose"
    throughputMode: "bursting"
    encrypted: true

  # S3 Buckets Configuration
  buckets:
    # Data bucket for storing Gen3 data
    dataBucket:
      name: "gen3-commons-data-859011005590-us-east-1"
      versioning: true
      encryption: true
    # Logging bucket for audit logs
    loggingBucket:
      name: "gen3-commons-logging-859011005590-us-east-1"
      versioning: false
      encryption: true
    # Upload bucket for user uploads
    uploadBucket:
      name: "gen3-commons-upload-859011005590-us-east-1"
      versioning: true
      encryption: true

  # KMS Configuration
  kms:
    description: "Gen3 commons encryption key"
    enableKeyRotation: true

  # OpenSearch Configuration
  opensearch:
    engineVersion: "OpenSearch_2.11"
    instanceType: "t3.small.search"
    instanceCount: 1
    volumeSize: 10

  # CloudWatch Logs Configuration
  cloudwatchLogs:
    retentionInDays: 1827

  # CloudTrail Configuration
  cloudtrail:
    enableLogFileValidation: true
    includeGlobalServiceEvents: true
    isMultiRegionTrail: true
