apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - infrastructure-instance.yaml
  - network-instance.yaml
  - security-instance.yaml
  - data-instance.yaml
  - compute-instance.yaml
