#!/usr/bin/env bash
###############################################################################
# push-ssm-secrets.sh
#
# Reads output.json (generated by generate-ssm-payload.sh) and creates or
# updates AWS Secrets Manager secrets using the AWS CLI.
#
# Usage:
#   bash push-ssm-secrets.sh [output.json] [--profile PROFILE] [--region REGION]
#
# Defaults:
#   output.json = outputs/ssm-repo-secrets/output.json
#   profile     = (from AWS_PROFILE env or none)
#   region      = us-east-1
###############################################################################
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUTS_DIR="${REPO_ROOT}/outputs"
LOG_DIR="${OUTPUTS_DIR}/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="${LOG_DIR}/ssm-push-$(date +%Y%m%d-%H%M%S).log"

main() {
OUTPUT_FILE="${REPO_ROOT}/outputs/ssm-repo-secrets/output.json"
AWS_PROFILE_ARG="${AWS_PROFILE:+--profile $AWS_PROFILE}"
AWS_REGION="${AWS_REGION:-us-east-1}"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      AWS_PROFILE_ARG="--profile $2"
      shift 2
      ;;
    --region)
      AWS_REGION="$2"
      shift 2
      ;;
    *)
      OUTPUT_FILE="$1"
      shift
      ;;
  esac
done

if [[ ! -f "$OUTPUT_FILE" ]]; then
  echo "=== No output.json found at $OUTPUT_FILE ==="
  echo "  Nothing to push — skipping."
  exit 0
fi

if ! command -v aws &>/dev/null; then
  echo "ERROR: AWS CLI not found" >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq not found" >&2
  exit 1
fi

# Check for empty repos list
REPO_COUNT_CHECK=$(jq '.repos | length' "$OUTPUT_FILE" 2>/dev/null || echo "0")
if [[ "$REPO_COUNT_CHECK" -eq 0 ]]; then
  echo "=== No repo secrets to push (empty repos list) ==="
  exit 0
fi

echo "=== Pushing Secrets to AWS Secrets Manager ==="
echo "  Input:   $OUTPUT_FILE"
echo "  Region:  $AWS_REGION"
echo "  Profile: ${AWS_PROFILE_ARG:-default}"
echo ""

REPO_COUNT=$(jq '.repos | length' "$OUTPUT_FILE")

for i in $(seq 0 $((REPO_COUNT - 1))); do
  REPO_NAME=$(jq -r ".repos[$i].name" "$OUTPUT_FILE")
  SSM_SECRET_NAME=$(jq -r ".repos[$i].ssm_secret_name" "$OUTPUT_FILE")
  SECRET_VALUE=$(jq -c ".repos[$i].payload" "$OUTPUT_FILE")

  echo "--- $REPO_NAME ---"
  echo "  Secret Name: $SSM_SECRET_NAME"

  # Check if secret already exists
  if aws secretsmanager describe-secret \
    --secret-id "$SSM_SECRET_NAME" \
    --region "$AWS_REGION" \
    $AWS_PROFILE_ARG &>/dev/null; then

    echo "  Secret exists — updating..."
    aws secretsmanager put-secret-value \
      --secret-id "$SSM_SECRET_NAME" \
      --secret-string "$SECRET_VALUE" \
      --region "$AWS_REGION" \
      $AWS_PROFILE_ARG

    echo "  Updated."

  else
    echo "  Secret does not exist — creating..."
    aws secretsmanager create-secret \
      --name "$SSM_SECRET_NAME" \
      --description "ArgoCD git repository credentials for $REPO_NAME" \
      --secret-string "$SECRET_VALUE" \
      --region "$AWS_REGION" \
      $AWS_PROFILE_ARG

    echo "  Created."
  fi

  echo ""
done

echo "=== Done: $REPO_COUNT secret(s) pushed to AWS Secrets Manager ==="
}

main "$@" 2>&1 | tee -a "$LOG_FILE"
exit "${PIPESTATUS[0]}"
