apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: gen3-gcp-storage-bucket.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  schema:
    apiVersion: v1alpha1
    kind: Gen3GcpStorageBucket
    spec:
      name: string
      project: string
      bucketName: string
      location: string | default="US"
      storageClass: string | default="STANDARD"
      versioning: boolean | default=true
      uniformBucketLevelAccess: boolean | default=true
    status:
      bucketID: ${bucket.status.id}
      bucketSelfLink: ${bucket.status.selfLink}
      bucketURL: ${bucket.status.url}

  resources:
  - id: bucket
    template:
      apiVersion: storage.cnrm.cloud.google.com/v1beta1
      kind: StorageBucket
      metadata:
        name: ${schema.spec.bucketName}
        namespace: ${schema.spec.name}
      spec:
        location: ${schema.spec.location}
        storageClass: ${schema.spec.storageClass}
        versioning:
          enabled: ${schema.spec.versioning}
        uniformBucketLevelAccess:
          enabled: ${schema.spec.uniformBucketLevelAccess}
        lifecycleRule:
          - action:
              type: Delete
            condition:
              age: 365
              withState: ARCHIVED
