apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spoke-fleet
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    type: fleet-management
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/indiana-university/gen3-kro
        revision: HEAD
        directories:
          - path: spokes/*
            exclude: spoke-template
  template:
    metadata:
      name: '{{.path.basename}}-fleet'
      labels:
        spoke: '{{.path.basename}}'
        type: fleet
    spec:
      project: default
      source:
        repoURL: https://github.com/indiana-university/gen3-kro
        targetRevision: HEAD
        path: '{{.path.path}}/argocd/base'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
