{{- if .Values.enableKROResourceGraphs }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro-resource-graphs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/indiana-university/gen3-kro.git
    targetRevision: staging
    path: argocd/hub/shared/kro-rgds/aws
  destination:
    server: https://kubernetes.default.svc
    namespace: kro-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
