apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: azure-aks.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  schema:
    apiVersion: v1alpha1
    kind: AzureAKS
    spec:
      name: string
      location: string
      resourceGroup: string
      vnetName: string
      subnetName: string
      kubernetesVersion: string | default="1.33"
      nodeCount: integer | default=2
      nodeVMSize: string | default="Standard_DS2_v2"
    status:
      clusterID: ${cluster.status.id}
      clusterName: ${cluster.status.name}
      clusterFQDN: ${cluster.status.fqdn}

  resources:
  - id: cluster
    template:
      apiVersion: containerservice.azure.com/v1api20231001
      kind: ManagedCluster
      metadata:
        name: ${schema.spec.name}
        namespace: ${schema.spec.name}
      spec:
        azureName: ${schema.spec.name}
        location: ${schema.spec.location}
        owner:
          name: ${schema.spec.resourceGroup}
        dnsPrefix: ${schema.spec.name}
        kubernetesVersion: ${schema.spec.version}
        agentPoolProfiles:
          - name: default
            count: ${schema.spec.nodeCount}
            vmSize: ${schema.spec.nodeVMSize}
            mode: System
            vnetSubnetReference:
              armId: ${schema.spec.vnetSubnetID}
        identity:
          type: SystemAssigned
        tags:
          Name: ${schema.spec.name}
          Environment: dev
