# Pod Identity configuration for ACK OPENSEARCHSERVICE controller
# Base values - can be overridden by tenant/environment/cluster specific values

podIdentityRole:
  description: "Pod Identity Role for ACK OPENSEARCHSERVICE Controller"
  managedPolicies: []
  policyRefs: []

podIdentityPolicy:
  description: "IAM Policy for ACK OPENSEARCHSERVICE Controller"
  policies: []
