# KRO controller resources
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
serviceAccount:
  name: ack-opensearchservice-sa
  create: false
featureGates:
  ResourceAdoption: true
