# This is a spoke cluster instance using the shared EKS RGD
# The actual RGD definition is in shared/kro-rgds/aws/eks-cluster-rgd.yaml
apiVersion: v1alpha1
kind: EksCluster
metadata:
  name: spoke-template-cluster
  namespace: default
spec:
  name: spoke-template
  tenant: auto1
  environment: staging
  region: us-west-2
  k8sVersion: "1.32"
  accountId: "REPLACE_WITH_SPOKE_ACCOUNT_ID"
  managementAccountId: "REPLACE_WITH_HUB_ACCOUNT_ID"
  adminRoleName: "Admin"
  fleetSecretManagerSecretNameSuffix: "argocd-secret"
  domainName: "spoke-template.example.com"
  
  vpc:
    create: true
    vpcCidr: "10.1.0.0/16"
    publicSubnet1Cidr: "10.1.1.0/24"
    publicSubnet2Cidr: "10.1.2.0/24"
    privateSubnet1Cidr: "10.1.11.0/24"
    privateSubnet2Cidr: "10.1.12.0/24"
  
  workloads: "false"
  
  gitops:
    addonsRepoBasePath: "hub/argocd/addons/"
    addonsRepoPath: "bootstrap"
    addonsRepoRevision: "main"
    addonsRepoUrl: "https://github.com/indiana-university/gen3-kro"
    
    fleetRepoBasePath: "hub/argocd/fleet/"
    fleetRepoPath: "bootstrap"
    fleetRepoRevision: "main"
    fleetRepoUrl: "https://github.com/indiana-university/gen3-kro"
    
    platformRepoBasePath: "hub/argocd/platform/"
    platformRepoPath: "bootstrap"
    platformRepoRevision: "main"
    platformRepoUrl: "https://github.com/indiana-university/gen3-kro"
    
    workloadRepoBasePath: "spokes/spoke-template/applications/"
    workloadRepoPath: ""
    workloadRepoRevision: "main"
    workloadRepoUrl: "https://github.com/indiana-university/gen3-kro"
  
  addons:
    enable_metrics_server: "true"
    enable_external_secrets: "true"
    enable_external_dns: "false"
    enable_kyverno: "true"
    enable_kyverno_policies: "true"
    enable_kyverno_policy_reporter: "true"
    enable_ack_iam: "true"
    enable_ack_eks: "true"
    enable_ack_efs: "true"
