apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: irsa-role.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-4"
spec:
  schema:
    apiVersion: v1alpha1
    kind: IRSARole
    spec:
      name: string
      region: string
      clusterName: string
      namespace: string
      serviceAccountName: string
      accountID: string
      oidcProvider: string
      policyARNs: "[]string | default=[]"
      inlinePolicyDocument: string | default=""
    status:
      roleARN: ${role.status.ackResourceMetadata.arn}
      roleName: ${role.spec.name}

  resources:
  - id: role
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        namespace: ${schema.spec.name}
        name: ${schema.spec.name}-irsa
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.name}-irsa
        description: "IRSA role for ${schema.spec.serviceAccountName}"
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "arn:aws:iam::${schema.spec.accountID}:oidc-provider/${schema.spec.oidcProvider}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "${schema.spec.oidcProvider}:sub": "system:serviceaccount:${schema.spec.namespace}:${schema.spec.serviceAccountName}",
                    "${schema.spec.oidcProvider}:aud": "sts.amazonaws.com"
                  }
                }
              }
            ]
          }
        policies: ${schema.spec.policyARNs}
        tags:
          - key: "Name"
            value: ${schema.spec.name}-irsa
          - key: "ServiceAccount"
            value: ${schema.spec.serviceAccountName}
          - key: "Namespace"
            value: ${schema.spec.namespace}
