apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - services.k8s.aws_adoptedresources.yaml
  - services.k8s.aws_fieldexports.yaml
  - wafv2.services.k8s.aws_ipsets.yaml
  - wafv2.services.k8s.aws_rulegroups.yaml
  - wafv2.services.k8s.aws_webacls.yaml
