---
# PostSync validation job for RGD instances
# Validates that ResourceGraphs are active after deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: rgd-postsync-validation
  namespace: argocd-ns
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: postsync-validator
      restartPolicy: Never
      containers:
        - name: validate
          image: bitnami/kubectl:1.27
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              echo "Running post-deployment validation for ResourceGraphs..."

              # Check ResourceGraphDefinitions
              echo "Validating ResourceGraphDefinitions..."
              RGDS=$(kubectl get resourcegraphdefinitions.kro.run -A --no-headers 2>/dev/null | wc -l || echo "0")
              echo "Found $RGDS ResourceGraphDefinition(s)"

              # Check each RGD status
              if [ "$RGDS" -gt 0 ]; then
                kubectl get resourcegraphdefinitions.kro.run -A -o json | \
                  jq -r '.items[] | "\(.metadata.name) \(.status.state // "unknown")"' | \
                  while read name state; do
                    if [ "$state" = "active" ] || [ "$state" = "Active" ]; then
                      echo "✓ RGD $name is active"
                    else
                      echo "⚠ RGD $name state: $state"
                    fi
                  done
              fi

              # Check ResourceGraph instances
              echo "Validating ResourceGraph instances..."
              RGS=$(kubectl get resourcegraphs.kro.run -A --no-headers 2>/dev/null | wc -l || echo "0")
              echo "Found $RGS ResourceGraph instance(s)"

              if [ "$RGS" -gt 0 ]; then
                FAILED=0
                kubectl get resourcegraphs.kro.run -A -o json | \
                  jq -r '.items[] | "\(.metadata.namespace)/\(.metadata.name) \(.status.state // "unknown")"' | \
                  while read rg state; do
                    if [ "$state" = "Active" ] || [ "$state" = "active" ]; then
                      echo "✓ ResourceGraph $rg is active"
                    elif [ "$state" = "Syncing" ] || [ "$state" = "syncing" ]; then
                      echo "⌛ ResourceGraph $rg is syncing"
                    else
                      echo "✗ ResourceGraph $rg state: $state"
                      FAILED=1
                    fi
                  done

                if [ "$FAILED" -eq 1 ]; then
                  echo "WARNING: Some ResourceGraphs are not in expected state"
                  echo "This may be normal if resources are still being created"
                fi
              fi

              echo "Post-deployment RGD validation completed"
