formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Modules

  This root module integrates the following submodules:

  | Module | Source | Description |
  |--------|--------|-------------|
  | vpc | ./modules/vpc | VPC and networking infrastructure |
  | eks_cluster | ./modules/eks-cluster | EKS cluster deployment |
  | ack_iam_policy | ./modules/ack-iam-policy | ACK IAM policy fetching and processing |
  | ack_pod_identity | ./modules/ack-pod-identity | ACK pod identity IAM roles |
  | ack_spoke_role | ./modules/ack-spoke-role | Cross-account ACK IAM roles |
  | cross_account_policy | ./modules/cross-account-policy | Cross-account assume role policies |
  | addons_pod_identities | ./modules/addons-pod-identities | Addon IAM roles (EBS CSI, External Secrets) |
  | argocd_deploy | ./modules/argocd-deploy | ArgoCD deployment and configuration |

  ## Resources

  {{ .Resources }}

  ## Inputs

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}

  ## Examples

  See `terraform.tfvars.example` for configuration examples.

  ## Usage

  ```hcl
  module "gen3_kro" {
    source = "./terraform"

    cluster_name = "my-eks-cluster"

    enable_vpc         = true
    enable_eks_cluster = true
    enable_ack         = true

    ack_services = {
      iam = { enabled = true }
      eks = { enabled = true }
    }
  }
  ```

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
