apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: test-gen3-aurora-subnet-group
  namespace: spoke1
  annotations:
    services.k8s.aws/region: us-east-1
    services.k8s.aws/adoption-policy: adopt-or-create
    services.k8s.aws/deletion-policy: delete
spec:
  name: test-gen3-aurora-subnet-group
  description: Subnet group for test-gen3 Aurora cluster
  subnetIDs:
    - subnet-05b1f5de3082698d3
    - subnet-09ec8e87dfbcbe1e8
  tags:
    - key: Name
      value: test-gen3-aurora-subnet-group
    - key: Environment
      value: dev
    - key: ManagedBy
      value: ACK
    - key: Project
      value: kro-test
