apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-root
  namespace: argocd
  labels:
    hub: <hub-name>
    role: hub
spec:
  project: hub
  source:
    repoURL: https://github.com/<org>/<repo>.git
    targetRevision: main
    path: argo/appsets/<hub-name>
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata
