apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ReplicationGroup
metadata:
  name: test-gen3-redis
  namespace: spoke1
  annotations:
    services.k8s.aws/region: us-east-1
    services.k8s.aws/adoption-policy: adopt-or-create
    services.k8s.aws/deletion-policy: delete
spec:
  replicationGroupID: test-gen3-redis
  description: test-gen3 ElastiCache Redis cluster
  engine: redis
  engineVersion: "7.0"
  cacheNodeType: cache.t3.micro
  numNodeGroups: 1
  replicasPerNodeGroup: 1
  cacheSubnetGroupName: test-gen3-cache-subnet-group
  securityGroupIDs:
    - sg-PLACEHOLDER
  atRestEncryptionEnabled: true
  kmsKeyID: arn:aws:kms:us-east-1:859011005590:key/69d29d2d-b8b6-4010-9290-08fcd662f261
  transitEncryptionEnabled: true
  authToken:
    namespace: spoke1
    name: test-gen3-redis-token
    key: token
  snapshotRetentionLimit: 7
  snapshotWindow: "03:00-05:00"
  automaticFailoverEnabled: true
  multiAZEnabled: true
  tags:
    - key: Name
      value: test-gen3-redis
    - key: Environment
      value: dev
    - key: ManagedBy
      value: ACK
    - key: Project
      value: kro-test
