# Override values for s3 ACK controller

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.s3}}"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
