apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: awsvpcendpointt1
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsVpcEndpointT1
    spec:
      name: string
      namespace: string | default="default"
      region: string | default="us-east-1"
      environment: string | default="dev"
      project: string | default="kro-managed"
      vpcID: string
      serviceName: string
      vpcEndpointType: string
      routeTableIDs: "[]string | default=[]"
      subnetIDs: "[]string | default=[]"
      securityGroupIDs: "[]string | default=[]"
      privateDNSEnabled: boolean | default=true
      adoptionPolicy: string | default="adopt-or-create"
      deletionPolicy: string | default="delete"
    status:
      vpcEndpointID: "${vpcEndpoint.status.vpcEndpointID}"
      state: "${vpcEndpoint.status.state}"
      conditions: "${vpcEndpoint.status.conditions}"
  resources:
  - id: vpcEndpoint
    readyWhen:
      - ${vpcEndpoint.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${vpcEndpoint.status.vpcEndpointID != ""}
      - ${vpcEndpoint.status.state == "available"}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: VPCEndpoint
      metadata:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: ${schema.spec.adoptionPolicy}
          services.k8s.aws/deletion-policy: ${schema.spec.deletionPolicy}
      spec:
        vpcID: ${schema.spec.vpcID}
        serviceName: ${schema.spec.serviceName}
        vpcEndpointType: ${schema.spec.vpcEndpointType}
        routeTableIDs: ${schema.spec.routeTableIDs}
        subnetIDs: ${schema.spec.subnetIDs}
        securityGroupIDs: ${schema.spec.securityGroupIDs}
        privateDNSEnabled: ${schema.spec.privateDNSEnabled}
        tags:
          - key: Name
            value: ${schema.spec.name}
          - key: Environment
            value: ${schema.spec.environment}
          - key: ManagedBy
            value: Kro
          - key: Project
            value: ${schema.spec.project}
          - key: Type
            value: ${schema.spec.vpcEndpointType}
