# Pod Identity configuration for ACK S3 controller
# Base values - can be overridden by tenant/environment/cluster specific values

podIdentityRole:
  description: "Pod Identity Role for ACK S3 Controller"
  managedPolicies: []
  policyRefs: []

podIdentityPolicy:
  description: "IAM Policy for ACK S3 Controller"
  policies: []
