
################################################################################
# Generate Files: Connect Script & ArgoCD Password
################################################################################

locals {
  outputs_dir = var.outputs_dir != "" ? var.outputs_dir : "${path.root}/outputs"
  stack_dir   = var.stack_dir != "" ? var.stack_dir : local.outputs_dir

  connect_script = <<-SCRIPT
#!/usr/bin/env bash
###############################################################################
# Connect to CSOC EKS Cluster & ArgoCD
# Generated by argocd-bootstrap terraform module
###############################################################################
set -euo pipefail

CLUSTER_NAME="${var.cluster_name}"
AWS_REGION="${var.region}"
AWS_PROFILE="${var.aws_profile}"

echo "=== Adding cluster to kubeconfig ==="
aws eks update-kubeconfig \
  --name "$CLUSTER_NAME" \
  --region "$AWS_REGION" \
  --alias "$CLUSTER_NAME" \
  $${AWS_PROFILE:+--profile "$AWS_PROFILE"}

echo "=== Verifying cluster connectivity ==="
if kubectl cluster-info --context "$CLUSTER_NAME" > /dev/null 2>&1; then
  echo "✓ Connected to cluster $CLUSTER_NAME"
else
  echo "✗ Could not verify cluster connectivity" >&2
fi

echo "=== Retrieving ArgoCD admin password ==="
ARGOCD_PASSWORD=""
for i in 1 2 3 4 5; do
  ARGOCD_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret \
    -o jsonpath="{.data.password}" --context "$CLUSTER_NAME" 2>/dev/null | base64 -d 2>/dev/null || true)
  if [[ -n "$ARGOCD_PASSWORD" ]]; then
    break
  fi
  echo "  waiting for argocd-initial-admin-secret... (attempt $i/5)"
  sleep 10
done

if [[ -n "$ARGOCD_PASSWORD" ]]; then
  echo "✓ ArgoCD admin password retrieved"
  echo "$ARGOCD_PASSWORD" > "${local.outputs_dir}/argocd-password.txt"
  # chmod may fail on NTFS bind-mounts — non-fatal
  chmod 600 "${local.outputs_dir}/argocd-password.txt" 2>/dev/null || true
  echo "  Saved to: ${local.outputs_dir}/argocd-password.txt"
else
  echo "✗ ArgoCD password not yet available (ArgoCD may still be deploying)"
fi

echo ""
echo "=== Starting ArgoCD port-forward (background) ==="
# Kill any existing port-forward on 8080
if lsof -ti:8080 >/dev/null 2>&1; then
  kill $(lsof -ti:8080) 2>/dev/null || true
  sleep 1
fi

# Use nohup + redirect so the port-forward:
#   1. Does not hold the parent pipeline (tee) open via stdout/stderr
#   2. Survives Ctrl+C / SIGHUP on the parent shell
PF_LOG="${local.outputs_dir}/port-forward.log"
nohup kubectl port-forward -n argocd svc/argocd-server 8080:443 \
  --context "$CLUSTER_NAME" > "$PF_LOG" 2>&1 &
PF_PID=$!
disown "$PF_PID"
sleep 2

if kill -0 "$PF_PID" 2>/dev/null; then
  echo "✓ ArgoCD UI available at: https://localhost:8080"
  echo "  Username: admin"
  if [[ -n "$ARGOCD_PASSWORD" ]]; then
    echo "  Password: $ARGOCD_PASSWORD"
  fi
  echo "  Port-forward PID: $PF_PID"
  echo "  Log: $PF_LOG"
  echo "  To stop: kill $PF_PID"
else
  echo "✗ Port-forward failed to start (see $PF_LOG)"
fi
SCRIPT
}

resource "local_file" "connect_script" {
  count           = var.enabled && var.stack_dir != "" ? 1 : 0
  content         = local.connect_script
  filename        = "${local.stack_dir}/connect-csoc.sh"
  file_permission = "0755"
}
