---
# Custom Health Check for KRO ResourceGraph and ResourceGraphDefinition
# This ConfigMap should be applied to the argocd namespace
# ArgoCD will automatically pick up custom health checks from ConfigMaps
# with the label "argocd.argoproj.io/secret-type: health-check"

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-kro-health-check
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: resource.customizations
data:
  # Health check for ResourceGraphDefinition
  resource.customizations.health.kro.run_ResourceGraphDefinition: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.state == "active" or obj.status.state == "Active" then
        hs.status = "Healthy"
        hs.message = "ResourceGraphDefinition is active and ready"
        return hs
      end
      if obj.status.state == "syncing" or obj.status.state == "Syncing" then
        hs.status = "Progressing"
        hs.message = "ResourceGraphDefinition is syncing"
        return hs
      end
      if obj.status.state == "failed" or obj.status.state == "Failed" then
        hs.status = "Degraded"
        hs.message = "ResourceGraphDefinition failed: " .. (obj.status.message or "unknown error")
        return hs
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for ResourceGraphDefinition status"
    return hs

  # Health check for ResourceGraph instances
  resource.customizations.health.kro.run_ResourceGraph: |
    hs = {}
    if obj.status ~= nil then
      -- Check for reconciliation status
      if obj.status.state == "Active" or obj.status.state == "active" then
        hs.status = "Healthy"
        hs.message = "ResourceGraph is active"
        return hs
      end
      if obj.status.state == "Syncing" or obj.status.state == "syncing" then
        hs.status = "Progressing"
        hs.message = "ResourceGraph is syncing"
        return hs
      end
      if obj.status.state == "Failed" or obj.status.state == "failed" then
        hs.status = "Degraded"
        hs.message = "ResourceGraph failed"
        return hs
      end
      -- Check conditions array
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" then
            if condition.status == "True" then
              hs.status = "Healthy"
              hs.message = "ResourceGraph is ready"
              return hs
            elseif condition.status == "False" then
              hs.status = "Degraded"
              hs.message = condition.message or "ResourceGraph not ready"
              return hs
            end
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for ResourceGraph to reconcile"
    return hs

  # Health check for dynamically created Vpc resource (example)
  resource.customizations.health.kro.run_Vpc: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.state == "Active" or obj.status.state == "active" then
        hs.status = "Healthy"
        hs.message = "VPC is active"
        return hs
      end
      if obj.status.state == "Syncing" or obj.status.state == "syncing" then
        hs.status = "Progressing"
        hs.message = "VPC is syncing"
        return hs
      end
      if obj.status.state == "Failed" or obj.status.state == "failed" then
        hs.status = "Degraded"
        hs.message = "VPC creation failed"
        return hs
      end
      -- Check for Ready condition
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" and condition.status == "True" then
            hs.status = "Healthy"
            hs.message = "VPC is ready"
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "VPC is being created"
    return hs
