apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - route53.services.k8s.aws_healthchecks.yaml
  - route53.services.k8s.aws_hostedzones.yaml
  - route53.services.k8s.aws_recordsets.yaml
  - services.k8s.aws_adoptedresources.yaml
  - services.k8s.aws_fieldexports.yaml
