apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-test-infrastructure.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsTestInfrastructure
    spec:
      name: string
      namespace: string
      overrideRegion: string | default=""
      environment: string | default="dev"
      tags: "map[string]string | default={}"

      # VPC Configuration
      vpc:
        cidr:
          vpcCidr: string | default="10.0.0.0/16"
          publicSubnet1Cidr: string | default="10.0.1.0/24"
          publicSubnet2Cidr: string | default="10.0.2.0/24"
          privateSubnet1Cidr: string | default="10.0.11.0/24"
          privateSubnet2Cidr: string | default="10.0.12.0/24"

      # EKS Configuration
      eks:
        enabled: boolean | default=true
        version: string | default="1.33"
        nodeGroupInstanceTypes: "[]string | default=[\"t3.large\"]"
        nodeGroupDesiredSize: integer | default=3
        nodeGroupMinSize: integer | default=2
        nodeGroupMaxSize: integer | default=6

      # RDS Configuration
      rds:
        enabled: boolean | default=true
        engine: string | default="postgres"
        engineVersion: string | default="15.4"
        instanceClass: string | default="db.t3.medium"
        allocatedStorage: integer | default=100
        databaseName: string | default="gen3"
        ingressIPRanges: "[]string | default=[\"10.0.0.0/8\"]"

      # Aurora Configuration (alternative to RDS)
      aurora:
        enabled: boolean | default=false
        engine: string | default="aurora-postgresql"
        engineVersion: string | default="15.4"
        instanceClass: string | default="db.r5.large"
        instanceCount: integer | default=2
        databaseName: string | default="gen3"
        ingressIPRanges: "[]string | default=[\"10.0.0.0/8\"]"

      # ElastiCache Configuration
      elasticache:
        enabled: boolean | default=true
        engine: string | default="redis"
        engineVersion: string | default="7.0"
        nodeType: string | default="cache.t3.micro"
        numCacheNodes: integer | default=1
        ingressIPRanges: "[]string | default=[\"10.0.0.0/8\"]"

      # EFS Configuration
      efs:
        enabled: boolean | default=false
        performanceMode: string | default="generalPurpose"
        throughputMode: string | default="bursting"
        encrypted: boolean | default=true
        kmsKeyID: string | default=""
        ingressIPRanges: "[]string | default=[\"10.0.0.0/8\"]"

      # S3 Data Bucket Configuration
      dataBucket:
        enabled: boolean | default=true
        bucketName: string
        versioning: boolean | default=true
        encryption: boolean | default=true
        publicAccess: boolean | default=false

      # KMS Configuration
      kms:
        enabled: boolean | default=true
        description: string | default="Gen3 encryption key"
        enableKeyRotation: boolean | default=true

      # OpenSearch Configuration
      opensearch:
        enabled: boolean | default=false
        engineVersion: string | default="OpenSearch_2.11"
        instanceType: string | default="t3.small.search"
        instanceCount: integer | default=1
        volumeSize: integer | default=10
        ingressIPRanges: "[]string | default=[\"10.0.0.0/8\"]"

      # Route53 Configuration
      route53:
        enabled: boolean | default=false
        zoneName: string | default=""
        privateZone: boolean | default=false
        comment: string | default="Gen3 hosted zone"

      # CloudTrail Configuration
      cloudtrail:
        enabled: boolean | default=false
        s3BucketName: string | default=""
        includeGlobalServiceEvents: boolean | default=true
        isMultiRegionTrail: boolean | default=true

      # WAF Configuration
      waf:
        enabled: boolean | default=false
        scope: string | default="REGIONAL"
        description: string | default="Gen3 WAF Web ACL"
        defaultAction: string | default="ALLOW"

    status:
      # VPC Outputs
      vpcID: ${vpc.status.vpcID}
      publicSubnet1ID: ${vpc.status.publicSubnet1ID}
      publicSubnet2ID: ${vpc.status.publicSubnet2ID}
      privateSubnet1ID: ${vpc.status.privateSubnet1ID}
      privateSubnet2ID: ${vpc.status.privateSubnet2ID}
      internetGatewayID: ${vpc.status.internetGatewayID}

      # EKS Outputs (conditional)
      eksClusterARN: ${eks.status.clusterARN}
      eksClusterName: ${eks.status.clusterName}
      eksClusterEndpoint: ${eks.status.clusterEndpoint}

      # Database Outputs (conditional - RDS or Aurora)
      dbInstanceARN: ${rds.status.dbInstanceARN}
      dbEndpoint: ${rds.status.endpoint}

      # ElastiCache Outputs (conditional)
      cacheClusterID: ${elasticache.status.cacheClusterID}
      cacheEndpoint: ${elasticache.status.endpoint}

      # EFS Outputs (conditional)
      efsFileSystemID: ${efs.status.fileSystemID}

      # S3 Outputs (conditional)
      dataBucketARN: ${dataBucket.status.bucketARN}
      dataBucketName: ${dataBucket.status.bucketName}

      # KMS Outputs (conditional)
      kmsKeyARN: ${kms.status.keyARN}
      kmsKeyID: ${kms.status.keyID}

  resources:
  # Layer 1: VPC (foundational - no dependencies)
  - id: vpc
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsVpc
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-vpc
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        cidr:
          vpcCidr: ${schema.spec.vpc.cidr.vpcCidr}
          publicSubnet1Cidr: ${schema.spec.vpc.cidr.publicSubnet1Cidr}
          publicSubnet2Cidr: ${schema.spec.vpc.cidr.publicSubnet2Cidr}
          privateSubnet1Cidr: ${schema.spec.vpc.cidr.privateSubnet1Cidr}
          privateSubnet2Cidr: ${schema.spec.vpc.cidr.privateSubnet2Cidr}

  # Layer 2: KMS (independent resource)
  - id: kms
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsKMS
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-kms
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        description: ${schema.spec.kms.description}
        enableKeyRotation: ${schema.spec.kms.enableKeyRotation}

  # Layer 3: EKS (depends on VPC)
  - id: eks
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsEKS
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-eks
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs:
          - ${vpc.status.privateSubnet1ID}
          - ${vpc.status.privateSubnet2ID}
        version: ${schema.spec.eks.version}
        nodeGroupInstanceTypes: ${schema.spec.eks.nodeGroupInstanceTypes}
        nodeGroupDesiredSize: ${schema.spec.eks.nodeGroupDesiredSize}
        nodeGroupMinSize: ${schema.spec.eks.nodeGroupMinSize}
        nodeGroupMaxSize: ${schema.spec.eks.nodeGroupMaxSize}

  # Layer 3: RDS (depends on VPC)
  - id: rds
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsRDS
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-rds
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs:
          - ${vpc.status.privateSubnet1ID}
          - ${vpc.status.privateSubnet2ID}
        ingressIPRanges: ${schema.spec.rds.ingressIPRanges}
        engine: ${schema.spec.rds.engine}
        engineVersion: ${schema.spec.rds.engineVersion}
        instanceClass: ${schema.spec.rds.instanceClass}
        allocatedStorage: ${schema.spec.rds.allocatedStorage}
        databaseName: ${schema.spec.rds.databaseName}

  # Layer 3: Aurora (alternative to RDS - depends on VPC)
  - id: aurora
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsAurora
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-aurora
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs:
          - ${vpc.status.privateSubnet1ID}
          - ${vpc.status.privateSubnet2ID}
        ingressIPRanges: ${schema.spec.aurora.ingressIPRanges}
        engine: ${schema.spec.aurora.engine}
        engineVersion: ${schema.spec.aurora.engineVersion}
        instanceClass: ${schema.spec.aurora.instanceClass}
        instanceCount: ${schema.spec.aurora.instanceCount}
        databaseName: ${schema.spec.aurora.databaseName}

  # Layer 3: ElastiCache (depends on VPC)
  - id: elasticache
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsElastiCache
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-elasticache
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs:
          - ${vpc.status.privateSubnet1ID}
          - ${vpc.status.privateSubnet2ID}
        ingressIPRanges: ${schema.spec.elasticache.ingressIPRanges}
        engine: ${schema.spec.elasticache.engine}
        engineVersion: ${schema.spec.elasticache.engineVersion}
        nodeType: ${schema.spec.elasticache.nodeType}
        numCacheNodes: ${schema.spec.elasticache.numCacheNodes}

  # Layer 3: EFS (depends on VPC)
  - id: efs
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsEFS
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-efs
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs:
          - ${vpc.status.privateSubnet1ID}
          - ${vpc.status.privateSubnet2ID}
        ingressIPRanges: ${schema.spec.efs.ingressIPRanges}
        performanceMode: ${schema.spec.efs.performanceMode}
        throughputMode: ${schema.spec.efs.throughputMode}
        encrypted: ${schema.spec.efs.encrypted}
        kmsKeyID: ${schema.spec.efs.kmsKeyID}

  # Layer 3: OpenSearch (depends on VPC)
  - id: opensearch
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsOpenSearch
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-opensearch
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs:
          - ${vpc.status.privateSubnet1ID}
          - ${vpc.status.privateSubnet2ID}
        ingressIPRanges: ${schema.spec.opensearch.ingressIPRanges}
        engineVersion: ${schema.spec.opensearch.engineVersion}
        instanceType: ${schema.spec.opensearch.instanceType}
        instanceCount: ${schema.spec.opensearch.instanceCount}
        volumeSize: ${schema.spec.opensearch.volumeSize}

  # Layer 2: Data Bucket (independent)
  - id: dataBucket
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsDataBucket
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-data-bucket
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        bucketName: ${schema.spec.dataBucket.bucketName}
        versioning: ${schema.spec.dataBucket.versioning}
        encryption: ${schema.spec.dataBucket.encryption}
        publicAccess: ${schema.spec.dataBucket.publicAccess}

  # Layer 2: Route53 (independent)
  - id: route53
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsRoute53
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-route53
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        zoneName: ${schema.spec.route53.zoneName}
        privateZone: ${schema.spec.route53.privateZone}
        vpcID: ${vpc.status.vpcID}
        vpcRegion: ${schema.spec.overrideRegion}
        comment: ${schema.spec.route53.comment}

  # Layer 2: CloudTrail (may depend on S3 bucket)
  - id: cloudtrail
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsCloudTrail
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cloudtrail
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        s3BucketName: ${schema.spec.cloudtrail.s3BucketName}
        includeGlobalServiceEvents: ${schema.spec.cloudtrail.includeGlobalServiceEvents}
        isMultiRegionTrail: ${schema.spec.cloudtrail.isMultiRegionTrail}

  # Layer 4: WAF (may depend on other resources)
  - id: waf
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsWAF
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-waf
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        scope: ${schema.spec.waf.scope}
        description: ${schema.spec.waf.description}
        defaultAction: ${schema.spec.waf.defaultAction}
