apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-generic-commons-and-bucket.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsGenericCommonsAndBucket
    spec:
      name: string
      namespace: string
      overrideRegion: string | default=""
      environment: string | default="dev"
      tags: "map[string]string | default={}"

      # Feature Toggles - control which resources are deployed
      features:
        enableVPC: boolean | default=true
        enableEKS: boolean | default=true
        enableAurora: boolean | default=true
        enableElastiCache: boolean | default=true
        enableEFS: boolean | default=true
        enableKMS: boolean | default=true
        enableOpenSearch: boolean | default=true
        enableCloudWatchLogs: boolean | default=true
        enableCloudTrail: boolean | default=true
        enableDataBucket: boolean | default=true
        enableLoggingBucket: boolean | default=true
        enableUploadBucket: boolean | default=true

      # VPC Configuration
      vpc:
        features:
          enableSubnet2: boolean | default=true
          enableSubnet3: boolean | default=false
          enableDbSubnet2: boolean | default=true
        cidr:
          vpcCidr: string | default="10.0.0.0/16"
          publicSubnet1Cidr: string | default="10.0.1.0/24"
          publicSubnet2Cidr: string | default="10.0.2.0/24"
          publicSubnet3Cidr: string | default="10.0.3.0/24"
          privateSubnet1Cidr: string | default="10.0.11.0/24"
          privateSubnet2Cidr: string | default="10.0.12.0/24"
          privateSubnet3Cidr: string | default="10.0.13.0/24"
          dbSubnet1Cidr: string | default="10.0.21.0/24"
          dbSubnet2Cidr: string | default="10.0.22.0/24"

      # EKS Configuration
      eks:
        version: string | default="1.33"
        nodeGroupInstanceTypes: "[]string | default=[\"t3.large\"]"
        nodeGroupDesiredSize: integer | default=3
        nodeGroupMinSize: integer | default=2
        nodeGroupMaxSize: integer | default=6

      # Aurora PostgreSQL Configuration
      aurora:
        engine: string | default="aurora-postgresql"
        engineVersion: string | default="15.4"
        instanceClass: string | default="db.r5.large"
        instanceCount: integer | default=2
        databaseName: string | default="gen3"
        masterUsername: string | default="admin"
        backupRetentionPeriod: integer | default=7

      # ElastiCache Configuration
      elasticache:
        engine: string | default="redis"
        engineVersion: string | default="7.0"
        nodeType: string | default="cache.t3.micro"
        numCacheNodes: integer | default=1

      # EFS Configuration
      efs:
        performanceMode: string | default="generalPurpose"
        throughputMode: string | default="bursting"
        encrypted: boolean | default=true

      # S3 Buckets Configuration
      buckets:
        # Data bucket
        dataBucket:
          name: string
          versioning: boolean | default=true
          encryption: boolean | default=true
        # Logging bucket
        loggingBucket:
          name: string
          versioning: boolean | default=false
          encryption: boolean | default=true
        # Upload bucket
        uploadBucket:
          name: string
          versioning: boolean | default=true
          encryption: boolean | default=true

      # KMS Configuration
      kms:
        description: string | default="Gen3 encryption key"
        enableKeyRotation: boolean | default=true

      # OpenSearch Configuration
      opensearch:
        engineVersion: string | default="OpenSearch_2.11"
        instanceType: string | default="t3.small.search"
        instanceCount: integer | default=1
        volumeSize: integer | default=10

      # CloudWatch Logs Configuration
      cloudwatchLogs:
        retentionInDays: integer | default=1827

      # CloudTrail Configuration
      cloudtrail:
        enableLogFileValidation: boolean | default=true
        includeGlobalServiceEvents: boolean | default=true
        isMultiRegionTrail: boolean | default=true

    status:
      # VPC Status
      vpc:
        vpcID: string | ${vpc.?status.?vpcID}
        publicSubnet1ID: string | ${vpc.?status.?publicSubnet1ID}
        publicSubnet2ID: string | ${vpc.?status.?publicSubnet2ID}
        publicSubnet3ID: string | ${vpc.?status.?publicSubnet3ID}
        privateSubnet1ID: string | ${vpc.?status.?privateSubnet1ID}
        privateSubnet2ID: string | ${vpc.?status.?privateSubnet2ID}
        privateSubnet3ID: string | ${vpc.?status.?privateSubnet3ID}
        dbSubnet1ID: string | ${vpc.?status.?dbSubnet1ID}
        dbSubnet2ID: string | ${vpc.?status.?dbSubnet2ID}
      # EKS Status
      eks:
        clusterName: string | ${eks.?status.?clusterName}
        clusterEndpoint: string | ${eks.?status.?clusterEndpoint}
        clusterARN: string | ${eks.?status.?clusterARN}
      # Aurora Status
      aurora:
        clusterEndpoint: string | ${aurora.?status.?clusterEndpoint}
        readerEndpoint: string | ${aurora.?status.?readerEndpoint}
      # ElastiCache Status
      elasticache:
        endpoint: string | ${elasticache.?status.?endpoint}
      # EFS Status
      efs:
        fileSystemID: string | ${efs.?status.?fileSystemID}
      # KMS Status
      kms:
        keyID: string | ${kms.?status.?keyID}
        keyARN: string | ${kms.?status.?keyARN}
      # S3 Buckets Status
      buckets:
        dataBucket:
          name: string | ${dataBucket.?status.?s3Name}
          arn: string | ${dataBucket.?status.?s3ARN}
        loggingBucket:
          name: string | ${loggingBucket.?status.?s3Name}
          arn: string | ${loggingBucket.?status.?s3ARN}
        uploadBucket:
          name: string | ${uploadBucket.?status.?s3Name}
          arn: string | ${uploadBucket.?status.?s3ARN}
      # OpenSearch Status
      opensearch:
        domainARN: string | ${opensearch.?status.?domainARN}
        domainEndpoint: string | ${opensearch.?status.?endpoint}
      # CloudWatch Logs Status
      cloudwatchLogs:
        logGroupARN: string | ${cloudwatchLogs.?status.?logGroupARN}
      # CloudTrail Status
      cloudtrail:
        trailARN: string | ${cloudtrail.?status.?trailARN}

  resources:
  # 1. KMS Key - needed for encryption of other resources
  - id: kms
    includeWhen:
      - ${schema.spec.features.enableKMS}
    readyWhen:
      - ${kms.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsKMS
      metadata:
        name: ${schema.spec.name}-kms
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        description: ${schema.spec.kms.description}
        enableKeyRotation: ${schema.spec.kms.enableKeyRotation}

  # 2. VPC - foundational network infrastructure
  - id: vpc
    includeWhen:
      - ${schema.spec.features.enableVPC}
    readyWhen:
      - ${vpc.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsVpc
      metadata:
        name: ${schema.spec.name}-vpc
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        cidr:
          vpcCidr: ${schema.spec.vpc.cidr.vpcCidr}
          publicSubnet1Cidr: ${schema.spec.vpc.cidr.publicSubnet1Cidr}
          publicSubnet2Cidr: ${schema.spec.vpc.cidr.publicSubnet2Cidr}
          publicSubnet3Cidr: ${schema.spec.vpc.cidr.publicSubnet3Cidr}
          privateSubnet1Cidr: ${schema.spec.vpc.cidr.privateSubnet1Cidr}
          privateSubnet2Cidr: ${schema.spec.vpc.cidr.privateSubnet2Cidr}
          privateSubnet3Cidr: ${schema.spec.vpc.cidr.privateSubnet3Cidr}
          dbSubnet1Cidr: ${schema.spec.vpc.cidr.dbSubnet1Cidr}
          dbSubnet2Cidr: ${schema.spec.vpc.cidr.dbSubnet2Cidr}
        features:
          enableSubnet2: ${schema.spec.vpc.features.enableSubnet2}
          enableSubnet3: ${schema.spec.vpc.features.enableSubnet3}
          enableDbSubnet1: ${ schema.spec.features.enableAurora || schema.spec.features.enableElastiCache || schema.spec.features.enableOpenSearch }
          enableDbSubnet2: ${schema.spec.vpc.features.enableDbSubnet2}

  # 3. CloudWatch Log Group - needed for CloudTrail and other logging
  - id: cloudwatchLogs
    includeWhen:
      - ${schema.spec.features.enableCloudWatchLogs}
    readyWhen:
      - ${cloudwatchLogs.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsCloudWatchLogs
      metadata:
        name: ${schema.spec.name}-logs
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        retentionInDays: ${schema.spec.cloudwatchLogs.retentionInDays}

  # 4. Logging S3 Bucket - needed for CloudTrail and other buckets
  - id: loggingBucket
    includeWhen:
      - ${schema.spec.features.enableLoggingBucket}
    readyWhen:
      - ${loggingBucket.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsS3Bucket
      metadata:
        name: ${schema.spec.buckets.loggingBucket.name}
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.buckets.loggingBucket.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        versioning: ${schema.spec.buckets.loggingBucket.versioning}
        encryption: ${schema.spec.buckets.loggingBucket.encryption}

  # 5. CloudTrail - depends on logging bucket and CloudWatch logs
  - id: cloudtrail
    includeWhen:
      - ${schema.spec.features.enableCloudTrail}
    readyWhen:
      - ${cloudtrail.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsCloudTrail
      metadata:
        name: ${schema.spec.name}-trail
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        s3BucketName: ${loggingBucket.status.s3Name}
        cloudWatchLogsLogGroupARN: ${cloudwatchLogs.status.logGroupARN}
        enableLogFileValidation: ${schema.spec.cloudtrail.enableLogFileValidation}
        includeGlobalServiceEvents: ${schema.spec.cloudtrail.includeGlobalServiceEvents}
        isMultiRegionTrail: ${schema.spec.cloudtrail.isMultiRegionTrail}
        kmsKeyID: ${kms.status.keyARN}

  # 6. EKS Cluster - depends on VPC
  - id: eks
    includeWhen:
      - ${schema.spec.features.enableEKS}
    readyWhen:
      - ${eks.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsEKS
      metadata:
        name: ${schema.spec.name}-eks
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs: "${ [vpc.status.privateSubnet1ID] + (schema.spec.vpc.features.enableSubnet2 ? [vpc.status.privateSubnet2ID] : []) + (schema.spec.vpc.features.enableSubnet3 ? [vpc.status.privateSubnet3ID] : []) }"
        version: ${schema.spec.eks.version}
        nodeGroupInstanceTypes: ${schema.spec.eks.nodeGroupInstanceTypes}
        nodeGroupDesiredSize: ${schema.spec.eks.nodeGroupDesiredSize}
        nodeGroupMinSize: ${schema.spec.eks.nodeGroupMinSize}
        nodeGroupMaxSize: ${schema.spec.eks.nodeGroupMaxSize}

  # 7. Aurora PostgreSQL - depends on VPC
  - id: aurora
    includeWhen:
      - ${schema.spec.features.enableAurora}
    readyWhen:
      - ${aurora.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsAurora
      metadata:
        name: ${schema.spec.name}-aurora
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs: "${ [vpc.status.dbSubnet1ID] + (schema.spec.vpc.features.enableDbSubnet2 ? [vpc.status.dbSubnet2ID] : []) }"
        ingressIPRanges: "${ [schema.spec.vpc.cidr.privateSubnet1Cidr] + (schema.spec.vpc.features.enableSubnet2 ? [schema.spec.vpc.cidr.privateSubnet2Cidr] : []) + (schema.spec.vpc.features.enableSubnet3 ? [schema.spec.vpc.cidr.privateSubnet3Cidr] : []) }"
        engine: ${schema.spec.aurora.engine}
        engineVersion: ${schema.spec.aurora.engineVersion}
        instanceClass: ${schema.spec.aurora.instanceClass}
        instanceCount: ${schema.spec.aurora.instanceCount}
        databaseName: ${schema.spec.aurora.databaseName}
        masterUsername: ${schema.spec.aurora.masterUsername}
        backupRetentionPeriod: ${schema.spec.aurora.backupRetentionPeriod}

  # 8. ElastiCache - depends on VPC
  - id: elasticache
    includeWhen:
      - ${schema.spec.features.enableElastiCache}
    readyWhen:
      - ${elasticache.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsElastiCache
      metadata:
        name: ${schema.spec.name}-elasticache
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs: "${ [vpc.status.dbSubnet1ID] + (schema.spec.vpc.features.enableDbSubnet2 ? [vpc.status.dbSubnet2ID] : []) }"
        ingressIPRanges: "${ [schema.spec.vpc.cidr.privateSubnet1Cidr] + (schema.spec.vpc.features.enableSubnet2 ? [schema.spec.vpc.cidr.privateSubnet2Cidr] : []) + (schema.spec.vpc.features.enableSubnet3 ? [schema.spec.vpc.cidr.privateSubnet3Cidr] : []) }"
        engine: ${schema.spec.elasticache.engine}
        engineVersion: ${schema.spec.elasticache.engineVersion}
        nodeType: ${schema.spec.elasticache.nodeType}
        numCacheNodes: ${schema.spec.elasticache.numCacheNodes}

  # 9. EFS - depends on VPC
  - id: efs
    includeWhen:
      - ${schema.spec.features.enableEFS}
    readyWhen:
      - ${efs.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsEFS
      metadata:
        name: ${schema.spec.name}-efs
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs: "${ [vpc.status.privateSubnet1ID] + (schema.spec.vpc.features.enableSubnet2 ? [vpc.status.privateSubnet2ID] : []) + (schema.spec.vpc.features.enableSubnet3 ? [vpc.status.privateSubnet3ID] : []) }"
        ingressIPRanges: "${ [schema.spec.vpc.cidr.privateSubnet1Cidr] + (schema.spec.vpc.features.enableSubnet2 ? [schema.spec.vpc.cidr.privateSubnet2Cidr] : []) + (schema.spec.vpc.features.enableSubnet3 ? [schema.spec.vpc.cidr.privateSubnet3Cidr] : []) }"
        performanceMode: ${schema.spec.efs.performanceMode}
        throughputMode: ${schema.spec.efs.throughputMode}
        encrypted: ${schema.spec.efs.encrypted}
        kmsKeyID: ${kms.status.keyID}

  # 10. Data Bucket - depends on KMS and logging bucket
  - id: dataBucket
    includeWhen:
      - ${schema.spec.features.enableDataBucket}
    readyWhen:
      - ${dataBucket.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsS3Bucket
      metadata:
        name: ${schema.spec.buckets.dataBucket.name}
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.buckets.dataBucket.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        versioning: ${schema.spec.buckets.dataBucket.versioning}
        encryption: ${schema.spec.buckets.dataBucket.encryption}

  # 11. Upload Bucket - depends on KMS and logging bucket
  - id: uploadBucket
    includeWhen:
      - ${schema.spec.features.enableUploadBucket}
    readyWhen:
      - ${uploadBucket.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsS3Bucket
      metadata:
        name: ${schema.spec.buckets.uploadBucket.name}
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.buckets.uploadBucket.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        versioning: ${schema.spec.buckets.uploadBucket.versioning}
        encryption: ${schema.spec.buckets.uploadBucket.encryption}

  # 12. OpenSearch - depends on VPC
  - id: opensearch
    includeWhen:
      - ${schema.spec.features.enableOpenSearch}
    readyWhen:
      - ${opensearch.status.conditions.exists(x, x.type == 'Ready' && x.status == "True")}
    template:
      apiVersion: kro.run/v1alpha1
      kind: AwsOpenSearch
      metadata:
        name: ${schema.spec.name}-opensearch
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
        overrideRegion: ${schema.spec.overrideRegion}
        environment: ${schema.spec.environment}
        tags: ${schema.spec.tags}
        vpcID: ${vpc.status.vpcID}
        subnetIDs: "${ [vpc.status.dbSubnet1ID] }"
        ingressIPRanges: "${ [schema.spec.vpc.cidr.privateSubnet1Cidr] + (schema.spec.vpc.features.enableSubnet2 ? [schema.spec.vpc.cidr.privateSubnet2Cidr] : []) + (schema.spec.vpc.features.enableSubnet3 ? [schema.spec.vpc.cidr.privateSubnet3Cidr] : []) }"
        engineVersion: ${schema.spec.opensearch.engineVersion}
        instanceType: ${schema.spec.opensearch.instanceType}
        instanceCount: ${schema.spec.opensearch.instanceCount}
        volumeSize: ${schema.spec.opensearch.volumeSize}
