apiVersion: kro.run/v1alpha1
kind: AwsCloudTrail
metadata:
  name: cloudtrail
  namespace: base
spec:
  name: base
  namespace: base
  overrideRegion: us-east-1
  environment: dev
  tags: {}
  s3BucketName: base-cloudtrail
  includeGlobalServiceEvents: true
  isMultiRegionTrail: true
  enableLogFileValidation: true
  cloudWatchLogsLogGroupARN: ""
  cloudWatchLogsRoleARN: ""
  kmsKeyID: ""
