apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - data
  - network
  - security
  - compute
  - data-t1-rgd.yaml
  - network-t1-rgd.yaml
  - security-t1-rgd.yaml
  - compute-t1-rgd.yaml
