cluster: "spoke1"
# accountNumber is injected at runtime via ArgoCD cluster Secret annotation

alb-controller:
  configuration:
    enabled: false

aws-s3-mountpoint:
  configuration:
    enabled: false

calico:
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  configuration:
    enabled: false

grafana-alloy:
  enabled: false
  configuration:
    enabled: false
karpenter:
  targetRevision: "1.0.8"

karpenter-crds:
  selectorTag: spoke1
  migration: false
  default:
    enabled: false
  jupyter:
    enabled: false
  workflow:
    enabled: false
