apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    type: controller
    component: kro
spec:
  project: default
  source:
    repoURL: ghcr.io
    chart: kro-run/kro/kro
    targetRevision: "0.2.1"
    helm:
      releaseName: kro
      values: |
        replicas: 2
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kro-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
