---
# Job that validates no CRs remain before allowing controller deletion
# This is a template - customize the CR_KINDS list per controller
apiVersion: batch/v1
kind: Job
metadata:
  name: controller-cleanup-check
  namespace: argocd-ns
  annotations:
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: controller-cleanup-checker
      restartPolicy: Never
      containers:
        - name: cr-check
          image: bitnami/kubectl:1.27
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              # List of CRD kinds managed by this controller (customize per controller)
              # Example for KRO: resourcegraphdefinitions, vpcs, etc.
              CR_KINDS="resourcegraphdefinitions.kro.run"

              echo "Checking for remaining custom resources..."
              FOUND_CRS=0
              for kind in $CR_KINDS; do
                COUNT=$(kubectl get "$kind" --all-namespaces --no-headers 2>/dev/null | wc -l || echo "0")
                if [ "$COUNT" -gt 0 ]; then
                  echo "WARNING: Found $COUNT instances of $kind"
                  kubectl get "$kind" --all-namespaces
                  FOUND_CRS=1
                fi
              done

              if [ "$FOUND_CRS" -eq 1 ]; then
                echo "ERROR: Custom resources still exist. Delete them before removing the controller."
                exit 1
              fi

              echo "No custom resources found. Safe to delete controller."
