apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-spoke-name
  annotations:
    policies.kyverno.io/title: Inject Instance Name
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: AwsGenericCommonsAndBucket
    policies.kyverno.io/description: >-
      This policy automatically injects instance name into
      AwsGenericCommonsAndBucket resources ONLY if namespace annotations exist.
      Otherwise, leaves spec values unchanged (uses existing or empty).
      Expected annotation: spec/name
spec:
  rules:
  - name: inject-name
    match:
      any:
      - resources:
          kinds:
          - AwsGenericCommonsAndBucket
    context:
    - name: namespaceSpokeName
      apiCall:
        urlPath: "/api/v1/namespaces/{{request.namespace}}"
        jmesPath: "metadata.annotations.\"spec/name\" || ''"
    preconditions:
      any:
      - key: "{{ namespaceSpokeName }}"
        operator: NotEquals
        value: ""
    mutate:
      patchStrategicMerge:
        spec:
          name: "{{ namespaceSpokeName }}"
