apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-spoke-account-id
  annotations:
    policies.kyverno.io/title: Inject Account ID
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: AwsGenericCommonsAndBucket
    policies.kyverno.io/description: >-
      This policy automatically injects AWS account ID into
      AwsGenericCommonsAndBucket resources ONLY if namespace annotations exist.
      Otherwise, leaves spec values unchanged (uses existing or empty).
      Expected annotations: services.k8s.aws/owner-account-id.
spec:
  rules:
  - name: inject-account-id
    match:
      any:
      - resources:
          kinds:
          - AwsGenericCommonsAndBucket
    preconditions:
      any:
      - key: "{{ request.namespace.metadata.annotations.\"services.k8s.aws/owner-account-id\" || '' }}"
        operator: NotEquals
        value: ""
    mutate:
      patchesJson6902: |-
        - op: replace
          path: /spec/accountId
          value: "{{ request.namespace.metadata.annotations.\"services.k8s.aws/owner-account-id\" }}"
