apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-aurora-password-secret
  annotations:
    policies.kyverno.io/title: Inject Aurora Password Secret Name
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Gen3Application
    policies.kyverno.io/description: >-
      This policy automatically injects Aurora password secret name into
      Gen3Application resources from namespace annotation.
      Expected annotation: gen3.io/aurora-password-secret.
spec:
  rules:
  - name: inject-aurora-password-secret
    match:
      any:
      - resources:
          kinds:
          - Gen3Application
    context:
    - name: auroraPasswordSecret
      apiCall:
        urlPath: "/api/v1/namespaces/{{request.namespace}}"
        jmesPath: "metadata.annotations.\"gen3.io/aurora-password-secret\" || ''"
    preconditions:
      any:
      - key: "{{ auroraPasswordSecret }}"
        operator: NotEquals
        value: ""
    mutate:
      patchStrategicMerge:
        spec:
          auroraPasswordSecretName: "{{ auroraPasswordSecret }}"
