# # Spoke Addons ApplicationSet
# #
# # This ApplicationSet deploys cluster addons (KRO, ACK controllers, and platform components)
# # to spoke clusters only (excludes CSOC/control-plane).
# #
# # Data Sources:
# # 1. Cluster Secret Annotations (from CSOC, propagated to spokes):
# #    - csoc_repo_url, csoc_repo_revision, csoc_repo_basepath
# #    - rgds_repo_url, rgds_path
# #
# # 2. Spoke ConfigMap ({spoke_alias}-argocd-settings):
# #    - addons.yaml: Service configs (namespace, serviceAccount, roleArn per addon)
# #    - gitops-context.yaml: spoke_alias, spoke_region, aws_region, and CSOC repo info
# #
# # 3. Addon Catalog (addons/csoc/catalog.yaml):
# #    - Defines available addons with Helm chart sources and versions
# #
# # 4. Enablement Configuration (per spoke): spokes/{spoke_alias}/addons/enablement.yaml
# #    - Controls which addons are deployed to each spoke cluster
# #
# # 5. Values Configuration (per spoke): spokes/{spoke_alias}/addons/values.yaml
# #    - Provides addon-specific configuration (resource limits, etc.)
# #
# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: spoke-addons
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   goTemplate: true
#   goTemplateOptions: ["missingkey=error"]
#   generators:
#     - matrix:
#         generators:
#           # Spoke clusters only (not the CSOC cluster itself)
#           - clusters:
#               selector:
#                 matchLabels:
#                   argocd.argoproj.io/secret-type: cluster
#               values:
#                 # Load spoke ConfigMap for addon configurations
#                 addonsConfigMap: '{{.name}}-argocd-settings'
#           # Addon catalog from git repository
#           - git:
#               repoURL: '{{.metadata.annotations.csoc_repo_url}}'
#               revision: '{{.metadata.annotations.csoc_repo_revision}}'
#               files:
#                 - path: 'argocd/addons/csoc/catalog.yaml'
#   template:
#     metadata:
#       name: '{{.name}}-{{.addon}}'
#       labels:
#         app.kubernetes.io/part-of: addons
#         app.kubernetes.io/name: '{{.addon}}'
#         cluster: '{{.name}}'
#         addon: '{{.addon}}'
#       annotations:
#         # KRO must be installed first (wave -1), cloud controllers at wave 0
#         argocd.argoproj.io/sync-wave: '{{if eq .addon "kro"}}"-1"{{else if or (hasPrefix "ack-" .addon) (hasPrefix "gcc-" .addon) (hasPrefix "aso-" .addon)}}"0"{{else}}"0"{{end}}'
#     spec:
#       project: default
#       sources:
#         # Addon Helm chart source
#         - repoURL: '{{.repoURL}}'
#           targetRevision: '{{.revision}}'
#           chart: '{{.chart}}'
#           helm:
#             valueFiles:
#               # Load values from spoke-specific location using spoke_alias from ConfigMap
#               - $values/spokes/{{.values.addonsConfigMap.data.gitops-context.spoke_alias}}/addons/values.yaml
#             # Addon-specific inline values
#             values: |
#               {{- if eq .addon "kro" }}
#               # KRO-specific configuration
#               image:
#                 tag: {{.revision}}
#               {{- end }}
#               {{- if hasPrefix "ack-" .addon }}
#               # ACK controller common configuration
#               # Get aws_region from spoke ConfigMap gitops-context
#               aws:
#                 region: {{.values.addonsConfigMap.data.gitops-context.aws_region}}
#               # Get service account and role ARN from spoke ConfigMap addons
#               # Note: Spoke ConfigMap contains CSOC's pod identity role ARNs (not spoke roles)
#               {{- $addonConfig := index .values.addonsConfigMap.data.addons .addon }}
#               serviceAccount:
#                 name: {{$addonConfig.serviceAccount}}
#                 annotations:
#                   eks.amazonaws.com/role-arn: {{$addonConfig.roleArn}}
#               {{- end }}
#         # Values repository reference for valueFiles
#         - repoURL: '{{.metadata.annotations.csoc_repo_url}}'
#           targetRevision: '{{.metadata.annotations.csoc_repo_revision}}'
#           ref: values
#       destination:
#         name: '{{.name}}'
#         # Namespace mapping: kro -> kro-system, ack-* -> ack-system, others use addon name
#         namespace: '{{if eq .addon "kro"}}kro-system{{else if hasPrefix "ack-" .addon}}ack-system{{else}}{{.addon}}-system{{end}}'
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#           allowEmpty: false
#         syncOptions:
#           - CreateNamespace=true
#           - ServerSideApply=true
#           - RespectIgnoreDifferences=true
#           - PrunePropagationPolicy=foreground
#           - PruneLast=true
#           - Replace=true  # Allow replacing resources including CRDs during sync
#         retry:
#           limit: 5
#           backoff:
#             duration: 5s
#             factor: 2
#             maxDuration: 3m
#       # Ignore differences in CRD conversion webhooks (common with large CRDs)
#       ignoreDifferences:
#         - group: apiextensions.k8s.io
#           kind: CustomResourceDefinition
#           jsonPointers:
#             - /spec/conversion/webhook/clientConfig/caBundle
#             - /status
