apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudtrail.services.k8s.aws_eventdatastores.yaml
  - cloudtrail.services.k8s.aws_trails.yaml
  - services.k8s.aws_fieldexports.yaml
  - services.k8s.aws_iamroleselectors.yaml
