apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: gen3-azure-postgresql.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  schema:
    apiVersion: v1alpha1
    kind: Gen3AzurePostgreSQL
    spec:
      name: string
      location: string
      resourceGroup: string
      vnetName: string
      subnetName: string
      version: string | default="16"
      skuName: string | default="Standard_B1ms"
      storageSizeGB: integer | default=32
    status:
      serverID: ${server.status.id}
      serverName: ${server.status.name}
      fqdn: ${server.status.fullyQualifiedDomainName}

  resources:
  - id: server
    template:
      apiVersion: dbforpostgresql.azure.com/v1api20230601preview
      kind: FlexibleServer
      metadata:
        name: ${schema.spec.serverName}
        namespace: ${schema.spec.name}
      spec:
        azureName: ${schema.spec.serverName}
        location: ${schema.spec.location}
        owner:
          name: ${schema.spec.resourceGroup}
        version: ${schema.spec.version}
        sku:
          name: ${schema.spec.skuName}
          tier: GeneralPurpose
        storage:
          storageSizeGB: ${schema.spec.storageSizeGB}
        administratorLogin: ${schema.spec.adminUsername}
        network:
          delegatedSubnetResourceReference:
            armId: ${schema.spec.subnetID}
        tags:
          Name: ${schema.spec.serverName}
          Environment: gen3
