apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: gen3-azure-storage-account.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  schema:
    apiVersion: v1alpha1
    kind: Gen3AzureStorageAccount
    spec:
      name: string
      location: string
      resourceGroup: string
      accountName: string
      sku: string | default="Standard_LRS"
      kind: string | default="StorageV2"
    status:
      storageAccountID: ${storageAccount.status.id}
      storageAccountName: ${storageAccount.status.name}
      primaryEndpoint: ${storageAccount.status.primaryEndpoints.blob}

  resources:
  - id: storageAccount
    template:
      apiVersion: storage.azure.com/v1api20230101
      kind: StorageAccount
      metadata:
        name: ${schema.spec.accountName}
        namespace: ${schema.spec.name}
      spec:
        azureName: ${schema.spec.accountName}
        location: ${schema.spec.location}
        owner:
          name: ${schema.spec.resourceGroup}
        kind: ${schema.spec.kind}
        sku:
          name: ${schema.spec.sku}
        properties:
          supportsHttpsTrafficOnly: true
          minimumTlsVersion: TLS1_2
          allowBlobPublicAccess: false
        tags:
          Name: ${schema.spec.accountName}
          Environment: gen3
