# Base configuration shared across all environments

hub:
  alias: "gen3-csoc"
  kubernetes_version: "1.33"
  vpc_name: "gen3-kro-vpc"

ack:
  namespace: "ack-system"
  user_provided_inline_policy_link: ""
  controllers:
    - cloudtrail
    - cloudwatchlogs
    - ec2
    - efs
    - eks
    - iam
    - kms
    - opensearchservice
    - rds
    - route53
    - s3
    - secretsmanager
    - sns
    - sqs
    - wafv2

gitops:
  org_name: "indiana-university"
  repo_name: "gen3-kro"
  github_url: "github.com"
  iam_config_raw_file_base_url: ""

paths:
  outputs_dir: "outputs"
  kubeconfig_dir: "outputs/kube"
  terraform_state_bucket: "gen3-kro-envs-4852"
  terraform_locks_table: "gen3-kro-terraform-locks"

deployment:
  argocd_chart_version: "5.46.0"
  kubeconfig_dir: "outputs/kube"

addons:
  enable_metrics_server: true
  enable_kyverno: true
  enable_kyverno_policies: true
  enable_kyverno_policy_reporter: true
  enable_argocd: true
  enable_cni_metrics_helper: false
  enable_kube_state_metrics: true
  enable_cert_manager: false
  enable_external_dns: false
  enable_external_secrets: true
  enable_ack_iam: true
  enable_ack_eks: true
  enable_ack_ec2: true
  enable_ack_efs: true
  enable_kro: true
  enable_kro_eks_rgs: true
  enable_multi_acct: true
  enable_aws_efs_csi_driver: false
  enable_aws_for_fluentbit: false
  enable_cw_prometheus: false
  enable_opentelemetry_operator: false
  enable_prometheus_node_exporter: false
