# terraform/config.yaml
# Centralized configuration for gen3-kro multi-account EKS platform
# This file replaces all .env files (controller-list.env, spokes-list.env, kro/core.env, kro/mods.env)
---
hub:
  alias: "gen3-csoc"                  # Alias for hub account
  aws_profile: "boadeyem_tf"  # AWS CLI profile for hub account (has access to S3 backend)
  aws_region: "us-east-1"     # Primary region for hub cluster
  cluster_name: "gen3-kro-hub"     # EKS cluster name
  kubernetes_version: "1.33"       # Kubernetes version
  vpc_name: "gen3-kro-vpc"         # VPC name for hub cluster

# ACK (AWS Controllers for Kubernetes) configuration
ack:
  namespace: "ack-system"
  user_provided_inline_policy_link: ""
  controllers:
    - cloudtrail
    - cloudwatchlogs
    - ec2
    - iam
    - kms
    - opensearchservice
    - rds
    - route53
    - s3
    - secretsmanager
    - sns
    - sqs
    - wafv2

# Spoke accounts for cross-account resource provisioning
spokes:
  - alias: "spoke1"
    region: "us-east-1"
    profile: "boadeyem_tf"  # Same account as hub for demo/testing
    account_id: ""  # Will be determined at runtime if empty
    tags:
      Team: "platform"
      Purpose: "multi-account-demo"

# GitOps repository configuration
gitops:
  org_name: "indiana-university"
  repo_name: "gen3-kro"
  github_url: "github.com"
  iam_config_raw_file_base_url: ""  # Leave empty to use default: "https://raw.githubusercontent.com/<org>/<repo>/<branch>"

  addons:
    base_path: "argocd/addons"
    path: "bootstrap"
    revision: "main"

  fleet:
    base_path: "argocd/fleet"
    path: "bootstrap"
    revision: "main"

  platform:
    base_path: "argocd/platform"
    path: "bootstrap"
    revision: "main"

  workload:
    base_path: "argocd/apps"
    path: "bootstrap"
    revision: "main"

# Output and state paths
paths:
  outputs_dir: "outputs"
  kubeconfig_dir: "outputs/kube"
  terraform_state_bucket: "gen3-kro-envs-4852"
  terraform_locks_table: "gen3-kro-terraform-locks" # Unused

# Deployment configuration
deployment:
  enable_cross_account_iam: true  # Enable cross-account IAM roles for spokes
  argocd_chart_version: "5.46.0"  # ArgoCD Helm chart version
  kubeconfig_dir: "outputs/kube"  # Directory for kubeconfig files

# Kubernetes addons configuration
addons:
  enable_metrics_server: true
  enable_kyverno: true
  enable_kyverno_policies: true
  enable_kyverno_policy_reporter: true
  enable_argocd: true
  enable_cni_metrics_helper: false
  enable_kube_state_metrics: true
  enable_cert_manager: false
  enable_external_dns: false
  enable_external_secrets: true
  enable_ack_iam: true
  enable_ack_eks: true
  enable_ack_ec2: true
  enable_ack_efs: true
  enable_kro: true
  enable_kro_eks_rgs: true
  enable_multi_acct: true
  enable_aws_efs_csi_driver: false
  enable_aws_for_fluentbit: false
  enable_cw_prometheus: false
  enable_opentelemetry_operator: false
  enable_prometheus_node_exporter: false

