# Production environment overrides
environment: prod
enable_cross_account_iam: true

# Cluster settings
cluster_name_suffix: prod
kubernetes_version: "1.33"

# Networking
vpc_cidr: "10.10.0.0/16"

# Addons - full suite for production
addons:
  enable_metrics_server: true
  enable_kyverno: true
  enable_kyverno_policies: true
  enable_kyverno_policy_reporter: true
  enable_external_secrets: true
  enable_cert_manager: true
  enable_external_dns: true
  enable_ack_iam: true
  enable_ack_eks: true
  enable_ack_ec2: true
  enable_kro: true

# ArgoCD settings
argocd:
  auto_sync: true
  self_heal: true
  prune: true
