hub:
  enable_argo: true
  old_cluster_name: "gen3-kro-hub-v2-staging"

deployment:
  enable_cross_account_iam: false

gitops:
  addons:
    revision: "staging"
  fleet:
    revision: "staging"
  platform:
    revision: "staging"
  workload:
    revision: "staging"
