hub:
  alias: "gen3-csoc"
  kubernetes_version: "1.33"
  vpc_name: "gen3-kro-vpc"
  aws_profile: "boadeyem_tf"
  aws_region: "us-east-1"
  cluster_name: "gen3-kro-hub"
  enable_argo: true
  old_cluster_name: ""

deployment:
  enable_cross_account_iam: false

gitops:
  addons:
    revision: "staging"
  fleet:
    revision: "staging"
  platform:
    revision: "staging"
  workload:
    revision: "staging"
