apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - vpc-instance.yaml

# Use replacements to customize instances per environment
replacements:
  - source:
      kind: Gen3Vpc
      name: gen3-vpc-dev
      fieldPath: spec.name
    targets:
      - select:
          kind: Gen3Vpc
          name: gen3-vpc-dev
        fieldPaths:
          - spec.name

# Patches for different environments
patches:
  # Development environment
  - target:
      kind: Gen3Vpc
      name: gen3-vpc-dev
    patch: |-
      - op: replace
        path: /spec/region
        value: us-east-1
      - op: replace
        path: /spec/cidr/vpcCidr
        value: "10.0.0.0/16"

# ConfigMap generator for environment-specific values
configMapGenerator:
  - name: gen3-vpc-config
    literals:
      - environment=dev
      - region=us-east-1

# Labels to apply to all resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: gen3
  environment: dev
