apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kms.services.k8s.aws_aliases.yaml
  - kms.services.k8s.aws_grants.yaml
  - kms.services.k8s.aws_keys.yaml
  - services.k8s.aws_adoptedresources.yaml
  - services.k8s.aws_fieldexports.yaml
