apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kro-hub
  namespace: argocd
  labels:
    hub: <hub-name>
spec:
  generators:
    - list:
        elements:
          - name: kro-hub-controllers
            path: argo/apps/kro/hub/controllers        # Helm chart in git
          - name: kro-hub-rgds
            path: argo/apps/kro/hub/rgds               # plain manifests or chart
  template:
    metadata:
      name: '{{name}}'
      labels:
        app.kubernetes.io/part-of: kro-hub
    spec:
      project: hub
      source:
        repoURL: https://github.com/<org>/<repo>.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - ../../values/common.yaml
            # add account/env matrix files if you want hub-specific tuning
      destination:
        server: https://kubernetes.default.svc
        namespace: kro-system
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions:
          - ServerSideApply=true
