apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kro-spokes
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/<org>/<repo>.git
        revision: main
        files:
          - path: argo/appsets/<hub-name>/spokes/*.yaml
  template:
    metadata:
      name: kro-{{name}}                 # `name:` field in each spoke YAML
      labels:
        hub: <hub-name>
        role: spoke
    spec:
      project: spokes
      source:
        repoURL: https://github.com/<org>/<repo>.git
        targetRevision: main
        path: argo/apps/kro/spoke/controllers
        helm:
          valuesObject:
            gitops: {{ gitops | toJson }}
            addons: {{ addons | toJson }}
      destination:
        server: '{{ server }}'           # you can add `server:` in the spoke YAML
        namespace: kro-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
