apiVersion: ec2.services.k8s.aws/v1alpha1
kind: SecurityGroup
metadata:
  name: test-gen3-eks-sg
  namespace: spoke1
  annotations:
    services.k8s.aws/region: us-east-1
    services.k8s.aws/adoption-policy: adopt-or-create
    services.k8s.aws/deletion-policy: delete
spec:
  name: test-gen3-eks-sg
  description: Security group for EKS cluster
  vpcID: vpc-099f7f9618636c63e
  tags:
    - key: Name
      value: test-gen3-eks-sg
    - key: Environment
      value: dev
    - key: ManagedBy
      value: ACK
    - key: Project
      value: kro-test
