apiVersion: eks.services.k8s.aws/v1alpha1
kind: Cluster
metadata:
  name: test-gen3-eks
  namespace: spoke1
  annotations:
    services.k8s.aws/region: us-east-1
    services.k8s.aws/adoption-policy: adopt-or-create
    services.k8s.aws/deletion-policy: delete
spec:
  name: test-gen3-eks
  version: "1.28"
  roleARN: REPLACE_WITH_CLUSTER_ROLE_ARN
  resourcesVPCConfig:
    subnetIDs:
      - subnet-08c996f8541d5cf07
      - subnet-0f5760ff2efbff1b7
    securityGroupIDs:
      - sg-PLACEHOLDER
    endpointPrivateAccess: true
    endpointPublicAccess: true
  encryptionConfig:
    - resources:
        - secrets
      provider:
        keyARN: arn:aws:kms:us-east-1:859011005590:key/0f241adb-9529-4246-bbe4-730761cc1e2c
  logging:
    clusterLogging:
      - types:
          - api
          - audit
          - authenticator
          - controllerManager
          - scheduler
        enabled: true
  tags:
    Name: test-gen3-eks
    Environment: dev
    ManagedBy: ACK
    Project: kro-test
