{{- $vals := .Values -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ default $vals.appSetName .Values.appSetName }}
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: '{{ default $vals.partOf .Values.partOf }}'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  fleet_member: control-plane
          - git:
              repoURL: '{{ default $vals.hubRepoURL .Values.hubRepoURL }}'
              revision: '{{ default $vals.hubRepoRevision .Values.hubRepoRevision }}'
              files:
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}'
  template:
    metadata:
      name: '{{`{{`}}.name{{`}}`}}-{{`{{`}}.path.basename{{`}}`}}-{{`{{`}}.items.addon{{`}}`}}'
      labels:
        app.kubernetes.io/part-of: '{{ default $vals.partOf .Values.partOf }}'
        app.kubernetes.io/name: '{{`{{`}}.items.addon{{`}}`}}'
        cluster: '{{`{{`}}.name{{`}}`}}'
        addon: '{{`{{`}}.items.addon{{`}}`}}'
        fleet-member: control-plane
    spec:
      project: '{{ $vals.appProject }}'
      sources:
        - repoURL: '{{`{{`}}.items.repoURL{{`}}`}}'
          targetRevision: '{{`{{`}}.items.revision{{`}}`}}'
          chart: '{{`{{`}}.items.chart{{`}}`}}'
          helm:
            valueFiles:
              - $values/{{ default $vals.valuesPath .Values.valuesPath }}
            values: |
              {{`{{-`}} if eq .items.addon "kro" {{`}}`}}
              image:
                tag: {{`{{`}}.items.revision{{`}}`}}
              {{`{{-`}} end {{`}}`}}
              {{`{{-`}} if hasPrefix "ack-" .items.addon {{`}}`}}
              {{`{{-`}} if .metadata.annotations.aws_region {{`}}`}}
              aws:
                region: {{`{{`}}.metadata.annotations.aws_region{{`}}`}}
              {{`{{-`}} end {{`}}`}}
              {{`{{-`}} end {{`}}`}}
        - repoURL: '{{ default $vals.hubRepoURL .Values.hubRepoURL }}'
          targetRevision: '{{ default $vals.hubRepoRevision .Values.hubRepoRevision }}'
          ref: values
      destination:
        name: '{{`{{`}}.name{{`}}`}}'
        namespace: '{{`{{`}}if eq .items.addon "kro"{{`}}`}}kro-system{{`{{`}}else if hasPrefix "ack-" .items.addon{{`}}`}}ack-system{{`{{`}}else{{`}}`}}{{`{{`}}.items.addon{{`}}`}}-system{{`{{`}}end{{`}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
{{- range $i, $opt := $vals.syncOptions }}
          - {{ $opt }}
{{- end }}
        retry:
          limit: {{ $vals.retry.limit }}
          backoff:
            duration: {{ $vals.retry.backoff.duration }}
            factor: {{ $vals.retry.backoff.factor }}
            maxDuration: {{ $vals.retry.backoff.maxDuration }}
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
            - /status
