{{- $vals := .Values -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ default $vals.appSetName .Values.appSetName }}
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: '{{ default $vals.partOf .Values.partOf }}'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  fleet_member: control-plane
          - git:
              repoURL: '{{ default $vals.hubRepoURL .Values.hubRepoURL }}'
              revision: '{{ default $vals.hubRepoRevision .Values.hubRepoRevision }}'
              files:
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/kro.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-cloudtrail.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-cloudwatchlogs.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-ec2.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-efs.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-eks.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-iam.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-kms.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-opensearchservice.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-rds.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-route53.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-s3.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-secretsmanager.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-sns.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-sqs.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/ack-wafv2.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/external-secrets.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/kyverno.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/kyverno-policies.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/metrics-server.yaml'
                - path: '{{ default $vals.catalogPath .Values.catalogPath }}/kube-state-metrics.yaml'
  template:
    metadata:
      name: '{{`{{`}}.name{{`}}`}}-{{`{{`}}.addon{{`}}`}}'
      labels:
        app.kubernetes.io/part-of: '{{ default $vals.partOf .Values.partOf }}'
        app.kubernetes.io/name: '{{`{{`}}.addon{{`}}`}}'
        cluster: '{{`{{`}}.name{{`}}`}}'
        addon: '{{`{{`}}.addon{{`}}`}}'
        fleet-member: control-plane
      annotations:
        argocd.argoproj.io/sync-wave: '{{`{{`}}if eq .addon "kro"{{`}}`}}"-1"{{`{{`}}else{{`}}`}}"0"{{`{{`}}end{{`}}`}}'
    spec:
      project: '{{ $vals.appProject }}'
      sources:
        - repoURL: '{{`{{`}}.repoURL{{`}}`}}'
          targetRevision: '{{`{{`}}.revision{{`}}`}}'
          chart: '{{`{{`}}.chart{{`}}`}}'
          helm:
            valueFiles:
              - $values/{{ default $vals.valuesPath $vals.valuesPath }}
            values: |
              {{`{{-`}} if eq .addon "kro" {{`}}`}}
              image:
                tag: {{`{{`}}.revision{{`}}`}}
              {{`{{-`}} end {{`}}`}}
              {{`{{-`}} if hasPrefix "ack-" .addon {{`}}`}}
              aws:
                region: {{`{{`}}.metadata.annotations.aws_region{{`}}`}}
              serviceAccount:
                annotations:
                  eks.amazonaws.com/role-arn: {{`{{`}}index .metadata.annotations (printf "%s_irsa_role_arn" .addon){{`}}`}}
              {{`{{-`}} end {{`}}`}}
        - repoURL: '{{ $vals.hubRepoURL }}'
          targetRevision: '{{ $vals.hubRepoRevision }}'
          ref: values
      destination:
        name: '{{`{{`}}.name{{`}}`}}'
        namespace: '{{`{{`}}if eq .addon "kro"{{`}}`}}kro-system{{`{{`}}else if hasPrefix "ack-" .addon{{`}}`}}ack-system{{`{{`}}else{{`}}`}}{{`{{`}}.addon{{`}}`}}-system{{`{{`}}end{{`}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
{{- range $i, $opt := $vals.syncOptions }}
          - {{ $opt }}
{{- end }}
        retry:
          limit: {{ $vals.retry.limit }}
          backoff:
            duration: {{ $vals.retry.backoff.duration }}
            factor: {{ $vals.retry.backoff.factor }}
            maxDuration: {{ $vals.retry.backoff.maxDuration }}
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
            - /status
