{{- $vals := .Values -}}
{{- $catalogPath := default $vals.catalogPath .Values.catalogPath -}}
{{- $hubRepoURL := default $vals.hubRepoURL .Values.hubRepoURL -}}
{{- $hubRepoRevision := default $vals.hubRepoRevision .Values.hubRepoRevision -}}
# This template generates a ConfigMap containing the list of addons for the list generator
# It's a workaround since ArgoCD's git file generator doesn't support array iteration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default $vals.appSetName .Values.appSetName }}-catalog
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: '{{ default $vals.partOf .Values.partOf }}'
data:
  catalog.yaml: |
    # This will be populated by a pre-sync hook or external process
    # that reads from the git repository catalog files
    # For now, we use an empty list as placeholder
    items: []
