apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ec2.services.k8s.aws_capacityreservations.yaml
  - ec2.services.k8s.aws_dhcpoptions.yaml
  - ec2.services.k8s.aws_elasticipaddresses.yaml
  - ec2.services.k8s.aws_flowlogs.yaml
  - ec2.services.k8s.aws_instances.yaml
  - ec2.services.k8s.aws_internetgateways.yaml
  - ec2.services.k8s.aws_launchtemplates.yaml
  - ec2.services.k8s.aws_managedprefixlists.yaml
  - ec2.services.k8s.aws_natgateways.yaml
  - ec2.services.k8s.aws_networkacls.yaml
  - ec2.services.k8s.aws_routetables.yaml
  - ec2.services.k8s.aws_securitygroups.yaml
  - ec2.services.k8s.aws_subnets.yaml
  - ec2.services.k8s.aws_transitgateways.yaml
  - ec2.services.k8s.aws_transitgatewayvpcattachments.yaml
  - ec2.services.k8s.aws_vpcendpointserviceconfigurations.yaml
  - ec2.services.k8s.aws_vpcendpoints.yaml
  - ec2.services.k8s.aws_vpcpeeringconnections.yaml
  - ec2.services.k8s.aws_vpcs.yaml
  - services.k8s.aws_fieldexports.yaml
  - services.k8s.aws_iamroleselectors.yaml
