apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gen3-network-sgs-t1-rgd.yaml
  - kms-t1-rgd.yaml
  - sg-alb-t1-rgd.yaml
  - sg-aurora-t1-rgd.yaml
  - sg-basic-conditional-t1-rgd.yaml
  - sg-efs-t1-rgd.yaml
  - sg-eks-cluster-t1-rgd.yaml
  - sg-eks-node-t1-rgd.yaml
  - sg-elasticache-t1-rgd.yaml
  - sg-opensearch-t1-rgd.yaml
  - sg-vpc-endpoints-t1-rgd.yaml
  - waf-alb-t1-rgd.yaml
