#!/usr/bin/env bash
###############################################################################
# MFA Session Helper — Write devcontainer credentials to isolated credentials dir
#
# Runs on the HOST (not inside the container). Writes AWS credentials for the
# devcontainer to ~/.aws/eks-devcontainer/credentials under [csoc].
# The devcontainer mounts ONLY that directory (not all of ~/.aws), so host
# profiles, static keys, and other credentials are never exposed.
#
# Option A — MFA (production, scoped devcontainer role):
#   bash scripts/mfa-session.sh <MFA_CODE>
#   Assumes the devcontainer role (e.g., {csoc_alias}-csoc-user) with MFA.
#   Temporary credentials expire after DURATION seconds (default 12h).
#
# Option B — No MFA (trusted dev environment, admin profile):
#   bash scripts/mfa-session.sh --no-mfa
#   Copies static credentials from SOURCE_PROFILE. No role assumption.
#
# All values (role_arn, source_profile, mfa_serial) are auto-detected from
# outputs/aws-config-snippet.ini (generated by terraform apply in
# terraform/env/developer-identity/).
#
# Usage:
#   bash scripts/mfa-session.sh <MFA_CODE> [--duration SECONDS]
#   bash scripts/mfa-session.sh 123456
#   bash scripts/mfa-session.sh --no-mfa [--profile SOURCE_PROFILE]
#
# Prerequisites:
#   1. terraform apply in terraform/env/developer-identity/ (generates snippet)
#   2. Virtual MFA device registered (for Option A only)
#
# Next Steps (after running this script):
#   1. Open (or rebuild) the devcontainer in VS Code
#      — ~/.aws/eks-devcontainer is bind-mounted as /home/vscode/.aws
#      — AWS_PROFILE=csoc is set automatically via containerEnv
#   2. Inside the container, verify credentials:
#        aws sts get-caller-identity
#   3. Run the Terraform orchestrator:
#        bash scripts/install.sh init    # backend init
#        bash scripts/install.sh plan    # review changes
#        bash scripts/install.sh apply   # provision EKS + ArgoCD bootstrap
#   4. If spoke IAM roles need (re)provisioning, run on the HOST first:
#        cd terragrunt/live/aws/<env> && terragrunt run-all apply
#   5. To tear down: bash scripts/destroy.sh  (inside the container)
###############################################################################
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="${REPO_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd -P)}"
OUTPUTS_DIR="${REPO_ROOT}/outputs"
LOG_DIR="${OUTPUTS_DIR}/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="${LOG_DIR}/mfa-session-$(date +%Y%m%d-%H%M%S).log"

main() {
# ─── Validate prerequisites ─────────────────────────────────────────────────
# jq is required for parsing STS assume-role JSON response
if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is not installed." >&2
  echo "  Install: brew install jq  (macOS)  or  sudo apt install jq  (Linux)" >&2
  exit 1
fi

# ─── Defaults (override via environment variables) ─────────────────────────
# Auto-detect source_profile from outputs/aws-config-snippet.ini if not set.
# That file is generated by: terraform apply in terraform/env/developer-identity/
_snippet="${REPO_ROOT}/outputs/aws-config-snippet.ini"
_auto_source=""
_auto_role=""
_auto_serial=""
if [[ -f "$_snippet" ]]; then
  _auto_source=$(grep -m1 'source_profile' "$_snippet" 2>/dev/null \
    | sed 's/.*=\s*//' | tr -d '[:space:]' || true)
  _auto_role=$(grep -m1 'role_arn' "$_snippet" 2>/dev/null \
    | sed 's/.*=\s*//' | tr -d '[:space:]' || true)
  _auto_serial=$(grep -m1 'mfa_serial' "$_snippet" 2>/dev/null \
    | sed 's/.*=\s*//' | tr -d '[:space:]' || true)
fi
SOURCE_PROFILE="${MFA_SOURCE_PROFILE:-${_auto_source}}"
if [[ -z "$SOURCE_PROFILE" ]]; then
  echo "ERROR: Could not determine source AWS profile." >&2
  echo "  Option 1: export MFA_SOURCE_PROFILE=<your-aws-profile>" >&2
  echo "  Option 2: run 'terraform apply' in terraform/env/developer-identity/" >&2
  echo "            to generate outputs/aws-config-snippet.ini (auto-detection)" >&2
  exit 1
fi

ROLE_ARN="${MFA_ROLE_ARN:-${_auto_role}}"
MFA_SERIAL="${MFA_SERIAL_ARN:-${_auto_serial}}"
SESSION_PROFILE="${MFA_SESSION_PROFILE:-csoc}"   # matches AWS_PROFILE=csoc in devcontainer
DURATION="${MFA_DURATION:-43200}"  # 12 hours
NO_MFA=0

# ─── Parse arguments ──────────────────────────────────────────────────────
MFA_CODE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --duration)
      DURATION="$2"; shift 2 ;;
    --profile)
      SOURCE_PROFILE="$2"; shift 2 ;;
    --role-arn)
      ROLE_ARN="$2"; shift 2 ;;
    --mfa-serial)
      MFA_SERIAL="$2"; shift 2 ;;
    --session-profile)
      SESSION_PROFILE="$2"; shift 2 ;;
    --no-mfa)
      NO_MFA=1; shift ;;
    --help|-h)
      echo "Usage: $0 <MFA_CODE> [--duration SECONDS] [--profile SOURCE_PROFILE]"
      echo "       [--role-arn ROLE_ARN] [--mfa-serial MFA_SERIAL_ARN]"
      echo "       [--session-profile SESSION_PROFILE_NAME] [--no-mfa]"
      echo ""
      echo "  --no-mfa    Option A: copy static creds from SOURCE_PROFILE (no role assumption)"
      echo "              Omit MFA_CODE when using this flag."
      echo ""
      echo "Environment variable overrides:"
      echo "  MFA_SOURCE_PROFILE   Source AWS profile (auto-detected from outputs/aws-config-snippet.ini)"
      echo "  MFA_ROLE_ARN         IAM role ARN to assume"
      echo "  MFA_SERIAL_ARN       MFA device serial number (ARN)"
      echo "  MFA_SESSION_PROFILE  Target credentials profile (default: csoc)"
      echo "  MFA_DURATION         Session duration in seconds (default: 43200 = 12h)"
      exit 0 ;;
    *)
      if [[ -z "$MFA_CODE" ]]; then
        MFA_CODE="$1"; shift
      else
        echo "ERROR: Unknown argument: $1" >&2; exit 1
      fi ;;
  esac
done

if [[ "$NO_MFA" -eq 0 ]] && [[ -z "$MFA_CODE" ]]; then
  echo "ERROR: MFA code is required (or use --no-mfa for admin profile without role assumption)." >&2
  echo "Usage: $0 <MFA_CODE> [--duration SECONDS]" >&2
  echo "       $0 --no-mfa [--profile SOURCE_PROFILE]" >&2
  exit 1
fi

# Validate MFA code format (6 digits)
if [[ "$NO_MFA" -eq 0 ]] && ! [[ "$MFA_CODE" =~ ^[0-9]{6}$ ]]; then
  echo "ERROR: MFA code must be exactly 6 digits." >&2
  exit 1
fi

# ─── Auto-detect role ARN and MFA serial from AWS config if still not set ──
if [[ -z "$ROLE_ARN" ]]; then
  ROLE_ARN=$(aws configure get role_arn --profile "$SESSION_PROFILE" 2>/dev/null || true)
fi
if [[ "$NO_MFA" -eq 0 ]] && [[ -z "$MFA_SERIAL" ]]; then
  MFA_SERIAL=$(aws configure get mfa_serial --profile "$SESSION_PROFILE" 2>/dev/null || true)
fi

# Fallback: detect MFA serial from IAM
if [[ "$NO_MFA" -eq 0 ]] && [[ -z "$MFA_SERIAL" ]]; then
  echo "Auto-detecting MFA serial from IAM..."
  MFA_SERIAL=$(aws iam list-mfa-devices --profile "$SOURCE_PROFILE" --output text \
    --query 'MFADevices[0].SerialNumber' 2>/dev/null || true)
fi

if [[ "$NO_MFA" -eq 0 ]] && [[ -z "$ROLE_ARN" ]]; then
  echo "ERROR: Could not determine role ARN." >&2
  echo "Set MFA_ROLE_ARN or ensure outputs/aws-config-snippet.ini exists (terraform apply)" >&2
  exit 1
fi

if [[ "$NO_MFA" -eq 0 ]] && [[ -z "$MFA_SERIAL" ]]; then
  echo "ERROR: Could not determine MFA serial number." >&2
  echo "Set MFA_SERIAL_ARN or run: aws iam list-mfa-devices --profile $SOURCE_PROFILE" >&2
  exit 1
fi

# ─── Resolve credentials directory (WSL-aware) ────────────────────────────
# devcontainer.json mounts:
#   source=${localEnv:HOME}${localEnv:USERPROFILE}/.aws/eks-devcontainer
# On Windows that resolves to C:\Users\<user>\.aws\eks-devcontainer (USERPROFILE).
# When this script runs inside WSL, $HOME is the Linux home (/home/<user>), which
# is a DIFFERENT path — Docker Desktop cannot mount it. Detect WSL and prefer
# the Windows home directory so the mounted path matches.
_resolve_creds_home() {
  # Git Bash / Windows native shell: USERPROFILE is already a Windows path
  if [[ -n "${USERPROFILE:-}" ]] && command -v wslpath &>/dev/null 2>&1; then
    wslpath "${USERPROFILE}" 2>/dev/null && return
  fi

  # WSL1 or WSL2: /proc/version contains "microsoft" or "Microsoft"
  if [[ -f /proc/version ]] && grep -qiE 'microsoft|WSL' /proc/version 2>/dev/null; then
    local _win_home=""

    # Preferred: wslvar (ships with WSL utilities on most distros)
    if command -v wslvar &>/dev/null; then
      _win_home="$(wslvar USERPROFILE 2>/dev/null | tr -d '\r' || true)"
    fi

    # Fallback: query cmd.exe directly
    if [[ -z "$_win_home" ]] && command -v cmd.exe &>/dev/null; then
      _win_home="$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r' || true)"
    fi

    if [[ -n "$_win_home" ]] && command -v wslpath &>/dev/null; then
      local _linux_path
      _linux_path="$(wslpath "${_win_home}" 2>/dev/null || true)"
      if [[ -n "$_linux_path" ]]; then
        echo "$_linux_path"
        return
      fi
    fi

    echo "  WARNING: Running in WSL but could not resolve Windows home." >&2
    echo "    Credentials will be written to WSL home ($HOME)." >&2
    echo "    If the devcontainer cannot see credentials, copy manually:" >&2
    echo "      cp -r ~/.aws/eks-devcontainer /mnt/c/Users/<WindowsUser>/.aws/" >&2
  fi

  # Native Linux / macOS — HOME is correct for Docker Desktop
  echo "${HOME}"
}
CREDS_HOME="$(_resolve_creds_home)"
CREDS_DIR="${CREDS_HOME}/.aws/eks-devcontainer"
mkdir -p "$CREDS_DIR"
echo "  Credentials dir: ${CREDS_DIR}"

# ─── Read source credentials BEFORE switching AWS_SHARED_CREDENTIALS_FILE ─
# aws configure get reads from the default credentials file; after we export
# the target file path, it would look for the source profile there instead.
_src_region="$(aws configure get region --profile "$SOURCE_PROFILE" 2>/dev/null || echo 'us-east-1')"

# ─── Acquire credentials ─────────────────────────────────────────────────
if [[ "$NO_MFA" -eq 1 ]]; then
  # Option A: copy static credentials from source profile (no role assumption)
  echo "Copying static credentials from '$SOURCE_PROFILE' to '$SESSION_PROFILE' (--no-mfa)..."
  _ak=$(aws configure get aws_access_key_id     --profile "$SOURCE_PROFILE" 2>/dev/null || true)
  _sk=$(aws configure get aws_secret_access_key --profile "$SOURCE_PROFILE" 2>/dev/null || true)
  if [[ -z "$_ak" ]] || [[ -z "$_sk" ]]; then
    echo "ERROR: Could not read credentials from profile '$SOURCE_PROFILE'." >&2
    exit 1
  fi

  # Now switch to the isolated credentials file for writing
  export AWS_SHARED_CREDENTIALS_FILE="${CREDS_DIR}/credentials"

  aws configure set aws_access_key_id     "$_ak"       --profile "$SESSION_PROFILE"
  aws configure set aws_secret_access_key "$_sk"       --profile "$SESSION_PROFILE"
  aws configure set region "$_src_region" --profile "$SESSION_PROFILE"
  # Clear any stale session token from a previous MFA session
  sed -i "/^\[${SESSION_PROFILE}\]/,/^\[/{/^aws_session_token/d}" \
    "$AWS_SHARED_CREDENTIALS_FILE" 2>/dev/null || true
  EXPIRATION="(static credentials — no expiry)"

  # ── Write session metadata for container-side tier detection ──────────
  cat > "${CREDS_DIR}/.session-meta" <<META
# Written by mfa-session.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
CREDENTIAL_TYPE=static
CREATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
SOURCE_PROFILE=${SOURCE_PROFILE}
SESSION_PROFILE=${SESSION_PROFILE}
META
else
  # Option B: assume role with MFA
  echo "Assuming role: $ROLE_ARN"
  echo "MFA device:   $MFA_SERIAL"
  echo "Duration:     ${DURATION}s ($(( DURATION / 3600 ))h)"
  echo ""

  # Read from default credentials (SOURCE_PROFILE) BEFORE switching files
  CREDS=$(aws sts assume-role \
    --role-arn "$ROLE_ARN" \
    --role-session-name "devcontainer-$(date +%s)" \
    --serial-number "$MFA_SERIAL" \
    --token-code "$MFA_CODE" \
    --duration-seconds "$DURATION" \
    --profile "$SOURCE_PROFILE" \
    --output json 2>&1)

  if [[ $? -ne 0 ]] || ! echo "$CREDS" | jq -e '.Credentials' &>/dev/null; then
    echo "ERROR: Failed to assume role." >&2
    echo "$CREDS" >&2
    exit 1
  fi

  # ── Extract and write temporary credentials ─────────────────────────────
  ACCESS_KEY=$(echo "$CREDS" | jq -r '.Credentials.AccessKeyId')
  SECRET_KEY=$(echo "$CREDS" | jq -r '.Credentials.SecretAccessKey')
  SESSION_TOKEN=$(echo "$CREDS" | jq -r '.Credentials.SessionToken')
  EXPIRATION=$(echo "$CREDS" | jq -r '.Credentials.Expiration')

  # Now switch to the isolated credentials file for writing
  export AWS_SHARED_CREDENTIALS_FILE="${CREDS_DIR}/credentials"

  aws configure set aws_access_key_id     "$ACCESS_KEY"     --profile "$SESSION_PROFILE"
  aws configure set aws_secret_access_key "$SECRET_KEY"     --profile "$SESSION_PROFILE"
  aws configure set aws_session_token     "$SESSION_TOKEN"  --profile "$SESSION_PROFILE"
  aws configure set region \
    "$(aws configure get region --profile "$SOURCE_PROFILE" 2>/dev/null || echo 'us-east-1')" \
    --profile "$SESSION_PROFILE"

  # ── Write session metadata for container-side tier detection ──────────
  cat > "${CREDS_DIR}/.session-meta" <<META
# Written by mfa-session.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
CREDENTIAL_TYPE=assumed-role
CREATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EXPIRY=${EXPIRATION}
DURATION_SECONDS=${DURATION}
ROLE_ARN=${ROLE_ARN}
SOURCE_PROFILE=${SOURCE_PROFILE}
SESSION_PROFILE=${SESSION_PROFILE}
META
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Session active until:  $EXPIRATION"
echo "  Credentials profile:   $SESSION_PROFILE"
echo "  Credentials file:      $AWS_SHARED_CREDENTIALS_FILE"
echo "  Log saved to:          $LOG_FILE"
echo ""
echo "  Devcontainer mounts:   ${CREDS_DIR} → /home/vscode/.aws"
echo "  (Docker Desktop resolves this from the Windows-side path)"
echo "  In the container:"
echo "    export AWS_PROFILE=$SESSION_PROFILE"
echo ""
echo "  Verify:"
echo "    aws sts get-caller-identity --profile $SESSION_PROFILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

main "$@" 2>&1 | tee -a "$LOG_FILE"
exit "${PIPESTATUS[0]}"
