apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: gen3s3bucket.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  schema:
    apiVersion: v1alpha1
    kind: Gen3S3Bucket
    spec:
      name: string
      region: string
      access: string | default="write"
      versioning: boolean | default=true
      encryption: boolean | default=true
    status:
      s3ARN: ${s3bucket.status.ackResourceMetadata.arn}
      s3Name: ${s3bucket.status.name}
      s3PolicyARN: ${s3Policy.status.ackResourceMetadata.arn}

  resources:
  - id: s3bucket
    template:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        namespace: ${schema.spec.name}
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.name}
        tags:
          - key: "Name"
            value: ${schema.spec.name}
          - key: "Environment"
            value: "gen3"
  - id: s3Policy
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Policy
      metadata:
        namespace: ${schema.spec.name}
        name: ${schema.spec.name}-s3-policy
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.name}-s3-policy
        policyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:GetObject",
                  "s3:PutObject",
                  "s3:PutObjectAcl",
                  "s3:DeleteObject"
                ],
                "Resource": [
                  "${s3bucket.status.ackResourceMetadata.arn}/*"
                ]
              },
              {
                "Effect": "Allow",
                "Action": [
                  "s3:ListBucket",
                  "s3:GetBucketLocation"
                ],
                "Resource": [
                  "${s3bucket.status.ackResourceMetadata.arn}"
                ]
              }
            ]
          }
