---
# Job that waits for critical CRDs to be Established
apiVersion: batch/v1
kind: Job
metadata:
  name: crd-established-check
  namespace: argocd-ns
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 5
  template:
    spec:
      serviceAccountName: crd-checker
      restartPolicy: OnFailure
      containers:
        - name: crd-wait
          image: bitnami/kubectl:1.27
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              echo "Waiting for KRO CRDs to be Established..."
              # List of critical KRO CRDs to wait for
              CRDS="resourcegraphdefinitions.kro.run"
              for crd in $CRDS; do
                echo "Checking $crd"
                until kubectl get crd "$crd" -o jsonpath='{.status.conditions[?(@.type=="Established")].status}' 2>/dev/null | grep -q True; do
                  echo "CRD $crd not yet established; sleeping 5s"
                  sleep 5
                done
                echo "$crd is Established"
              done
              echo "All required CRDs are Established."
