apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: gcp-cloudsql.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  schema:
    apiVersion: v1alpha1
    kind: CloudSQL
    spec:
      name: string
      project: string
      region: string
      vpcName: string
      databaseVersion: string | default="POSTGRES_15"
      tier: string | default="db-f1-micro"
      diskSize: integer | default=20
    status:
      instanceID: ${instance.status.id}
      instanceConnectionName: ${instance.status.connectionName}
      instanceSelfLink: ${instance.status.selfLink}
      databaseID: ${database.status.id}

  resources:
  - id: instance
    template:
      apiVersion: sql.cnrm.cloud.google.com/v1beta1
      kind: SQLInstance
      metadata:
        name: ${schema.spec.instanceName}
        namespace: ${schema.spec.name}
      spec:
        databaseVersion: ${schema.spec.databaseVersion}
        region: ${schema.spec.region}
        settings:
          tier: ${schema.spec.tier}
          diskSize: ${schema.spec.diskSize}
          ipConfiguration:
            ipv4Enabled: false
            privateNetworkRef:
              name: ${schema.spec.name}-vpc
          backupConfiguration:
            enabled: true
            startTime: "02:00"

  - id: database
    template:
      apiVersion: sql.cnrm.cloud.google.com/v1beta1
      kind: SQLDatabase
      metadata:
        name: ${schema.spec.databaseName}
        namespace: ${schema.spec.name}
      spec:
        instanceRef:
          name: ${instance.metadata.name}
