apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro-rgds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    type: kro-definitions
spec:
  project: default
  source:
    repoURL: https://github.com/indiana-university/gen3-kro
    targetRevision: HEAD
    path: shared/kro-rgds
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
