apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elasticache.services.k8s.aws_cacheclusters.yaml
  - elasticache.services.k8s.aws_cacheparametergroups.yaml
  - elasticache.services.k8s.aws_cachesubnetgroups.yaml
  - elasticache.services.k8s.aws_replicationgroups.yaml
  - elasticache.services.k8s.aws_serverlesscachesnapshots.yaml
  - elasticache.services.k8s.aws_serverlesscaches.yaml
  - elasticache.services.k8s.aws_snapshots.yaml
  - elasticache.services.k8s.aws_usergroups.yaml
  - elasticache.services.k8s.aws_users.yaml
  - services.k8s.aws_fieldexports.yaml
  - services.k8s.aws_iamroleselectors.yaml
