apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-aurora.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsAurora
    spec:
      name: string
      namespace: string
      region: string | default=""
      environment: string | default="dev"
      project: string | default="kro-managed"
      vpcID: string
      subnetIDs: "[]string"
      ingressIPRanges: "[]string | default=[\"10.0.0.0/8\"]"
      engine: string | default="aurora-postgresql"
      engineVersion: string | default="15.4"
      instanceClass: string | default="db.r5.large"
      instanceCount: integer | default=2
      databaseName: string
      masterUsername: string | default="admin"
      backupRetentionPeriod: integer | default=7
      preferredBackupWindow: string | default="03:00-04:00"
      preferredMaintenanceWindow: string | default="sun:04:00-sun:05:00"
      kmsKeyARN: string | default=""
    status:
      clusterARN: ${cluster.status.ackResourceMetadata.arn}
      clusterID: ${cluster.spec.dbClusterIdentifier}
      clusterEndpoint: ${cluster.status.endpoint}
      readerEndpoint: ${cluster.status.readerEndpoint}
      # AWS-managed master password secret (when manageMasterUserPassword: true)
      # Secret contains: username, password, engine, host, port, dbname, dbClusterIdentifier
      # Naming pattern: rds!cluster-{dbClusterIdentifier}-{random-6-char}
      # Example: rds!cluster-my-gen3-commons-aurora-a1b2c3
      masterPasswordSecretARN: ${cluster.status.masterUserSecret.secretARN}

  resources:
  - id: dbSubnetGroup
    template:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBSubnetGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-aurora-subnet-group
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.name}-aurora-subnet-group
        description: "Aurora cluster subnet group"
        subnetIDs: ${schema.spec.subnetIDs}
        tags:
        - key: Name
          value: ${schema.spec.name}-aurora-subnet-group
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: securityGroup
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-aurora-sg
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.name}-aurora-sg
        description: "Aurora cluster security group"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 5432
            toPort: 5432
            ipProtocol: tcp
            ipRanges:
              - cidrIP: ${schema.spec.ingressIPRanges[0]}
              - cidrIP: ${schema.spec.ingressIPRanges[1]}
        tags:
        - key: Name
          value: ${schema.spec.name}-aurora-sg
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: cluster
    template:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBCluster
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-aurora
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        dbClusterIdentifier: ${schema.spec.name}-aurora
        engine: ${schema.spec.engine}
        engineVersion: ${schema.spec.engineVersion}
        databaseName: ${schema.spec.databaseName}
        masterUsername: ${schema.spec.masterUsername}
        manageMasterUserPassword: true
        dbSubnetGroupName: ${dbSubnetGroup.spec.name}
        vpcSecurityGroupIDs:
          - ${securityGroup.status.id}
        backupRetentionPeriod: ${schema.spec.backupRetentionPeriod}
        preferredBackupWindow: ${schema.spec.preferredBackupWindow}
        preferredMaintenanceWindow: ${schema.spec.preferredMaintenanceWindow}
        storageEncrypted: true
        kmsKeyID: ${schema.spec.kmsKeyARN}
        enableCloudwatchLogsExports:
          - postgresql
        tags:
        - key: Name
          value: ${schema.spec.name}-aurora
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: instance1
    template:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBInstance
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-aurora-instance-1
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        dbInstanceIdentifier: ${schema.spec.name}-aurora-instance-1
        dbInstanceClass: ${schema.spec.instanceClass}
        engine: ${schema.spec.engine}
        dbClusterIdentifier: ${cluster.spec.dbClusterIdentifier}
        publiclyAccessible: false
        tags:
        - key: Name
          value: ${schema.spec.name}-aurora-instance-1
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: instance2
    includeWhen:
      - ${schema.spec.instanceCount >= 2}
    template:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBInstance
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-aurora-instance-2
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        dbInstanceIdentifier: ${schema.spec.name}-aurora-instance-2
        dbInstanceClass: ${schema.spec.instanceClass}
        engine: ${schema.spec.engine}
        dbClusterIdentifier: ${cluster.spec.dbClusterIdentifier}
        publiclyAccessible: false
        tags:
        - key: Name
          value: ${schema.spec.name}-aurora-instance-2
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
