apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aurora.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsAurora
    spec:
      name: string
      namespace: string
      overrideRegion: string | default=""
      environment: string | default="dev"
      tags: "map[string]string | default={}"
      vpcID: string
      subnetIDs: "[]string"
      ingressCIDR: string | default="10.0.0.0/8"
      engine: string | default="aurora-postgresql"
      engineVersion: string | default="15.4"
      instanceClass: string | default="db.r5.large"
      instanceCount: integer | default=2
      databaseName: string
      masterUsername: string | default="admin"
      backupRetentionPeriod: integer | default=7
      preferredBackupWindow: string | default="03:00-04:00"
      preferredMaintenanceWindow: string | default="sun:04:00-sun:05:00"
    status:
      clusterARN: ${cluster.status.ackResourceMetadata.arn}
      clusterID: ${cluster.spec.dbClusterIdentifier}
      clusterEndpoint: ${cluster.status.endpoint}
      readerEndpoint: ${cluster.status.readerEndpoint}

  resources:
  - id: dbSubnetGroup
    template:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBSubnetGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-aurora-subnet-group
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        name: ${schema.spec.name}-aurora-subnet-group
        description: "Aurora cluster subnet group"
        subnetIDs: ${schema.spec.subnetIDs}
        tags:
          - key: "Name"
            value: ${schema.spec.name}-aurora-subnet-group
          - key: "Environment"
            value: ${schema.spec.environment}
  - id: securityGroup
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-aurora-sg
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        name: ${schema.spec.name}-aurora-sg
        description: "Aurora cluster security group"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 5432
            toPort: 5432
            ipProtocol: tcp
            ipRanges:
              - cidrIP: ${schema.spec.ingressCIDR}
        tags:
          - key: "Name"
            value: ${schema.spec.name}-aurora-sg
          - key: "Environment"
            value: ${schema.spec.environment}
  - id: cluster
    template:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBCluster
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-aurora
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        dbClusterIdentifier: ${schema.spec.name}-aurora
        engine: ${schema.spec.engine}
        engineVersion: ${schema.spec.engineVersion}
        databaseName: ${schema.spec.databaseName}
        masterUsername: ${schema.spec.masterUsername}
        dbSubnetGroupName: ${dbSubnetGroup.spec.name}
        vpcSecurityGroupIDs:
          - ${securityGroup.status.id}
        backupRetentionPeriod: ${schema.spec.backupRetentionPeriod}
        preferredBackupWindow: ${schema.spec.preferredBackupWindow}
        preferredMaintenanceWindow: ${schema.spec.preferredMaintenanceWindow}
        storageEncrypted: true
        enableCloudwatchLogsExports:
          - postgresql
        tags:
          - key: "Name"
            value: ${schema.spec.name}-aurora
          - key: "Environment"
            value: ${schema.spec.environment}
