apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: cloudwatchlogs.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsCloudWatchLogs
    spec:
      name: string
      namespace: string
      overrideRegion: string | default=""
      environment: string | default="dev"
      tags: "map[string]string | default={}"
      logGroupName: string
      retentionInDays: integer | default=30
      kmsKeyID: string | default=""
    status:
      logGroupARN: ${logGroup.status.ackResourceMetadata.arn}
      logGroupName: ${logGroup.spec.name}

  resources:
  - id: logGroup
    template:
      apiVersion: cloudwatchlogs.services.k8s.aws/v1alpha1
      kind: LogGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        name: ${schema.spec.logGroupName}
        retentionDays: ${schema.spec.retentionInDays}
        kmsKeyID: ${schema.spec.kmsKeyID}
        tags:
          Name: ${schema.spec.name}
          Environment: "dev"
