apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-cloudtrail.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsCloudTrail
    spec:
      name: string
      namespace: string
      region: string | default=""
      environment: string | default="dev"
      project: string | default="kro-managed"
      s3BucketName: string
      includeGlobalServiceEvents: boolean | default=true
      isMultiRegionTrail: boolean | default=true
      enableLogFileValidation: boolean | default=true
      cloudWatchLogsLogGroupARN: string | default=""
      cloudWatchLogsRoleARN: string | default=""
      kmsKeyARN: string | default=""
      accountId: string
    status:
      trailARN: ${trail.?status.?ackResourceMetadata.?arn}

  resources:
  - id: bucketPolicy
    template:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.s3BucketName}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.s3BucketName}
        policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "AWSCloudTrailAclCheck",
                "Effect": "Allow",
                "Principal": {
                  "Service": "cloudtrail.amazonaws.com"
                },
                "Action": "s3:GetBucketAcl",
                "Resource": "arn:aws:s3:::${schema.spec.s3BucketName}"
              },
              {
                "Sid": "AWSCloudTrailWrite",
                "Effect": "Allow",
                "Principal": {
                  "Service": "cloudtrail.amazonaws.com"
                },
                "Action": "s3:PutObject",
                "Resource": "arn:aws:s3:::${schema.spec.s3BucketName}/AWSLogs/${schema.spec.accountId}/*",
                "Condition": {
                  "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                  }
                }
              }
            ]
          }
  - id: cloudwatchRole
    includeWhen:
      - ${schema.spec.cloudWatchLogsLogGroupARN != ""}
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cloudtrail-cw-role
      spec:
        name: ${schema.spec.name}-cloudtrail-cloudwatch-role
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "cloudtrail.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }
        policies:
        - ${cloudwatchPolicy.status.ackResourceMetadata.arn}
        tags:
        - key: Name
          value: ${schema.spec.name}-cloudtrail-cloudwatch-role
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: cloudwatchPolicy
    includeWhen:
      - ${schema.spec.cloudWatchLogsLogGroupARN != ""}
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Policy
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cloudtrail-cw-policy
      spec:
        name: ${schema.spec.name}-cloudtrail-cloudwatch-policy
        policyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "logs:CreateLogStream",
                  "logs:PutLogEvents"
                ],
                "Resource": "${schema.spec.cloudWatchLogsLogGroupARN}:*"
              }
            ]
          }
        tags:
        - key: Name
          value: ${schema.spec.name}-cloudtrail-cloudwatch-policy
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: trail
    template:
      apiVersion: cloudtrail.services.k8s.aws/v1alpha1
      kind: Trail
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.name}
        s3BucketName: ${schema.spec.s3BucketName}
        includeGlobalServiceEvents: ${schema.spec.includeGlobalServiceEvents}
        isMultiRegionTrail: ${schema.spec.isMultiRegionTrail}
        enableLogFileValidation: ${schema.spec.enableLogFileValidation}
        cloudWatchLogsLogGroupARN: ${schema.spec.cloudWatchLogsLogGroupARN}
        cloudWatchLogsRoleARN: "${ schema.spec.cloudWatchLogsLogGroupARN != \"\" ? cloudwatchRole.status.ackResourceMetadata.arn : \"\" }"
        kmsKeyID: ${schema.spec.kmsKeyARN}
        tags:
        - key: Name
          value: ${schema.spec.name}
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
