apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-databucket.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsDataBucket
    spec:
      name: string
      namespace: string
      region: string | default=""
      environment: string | default="dev"
      tags: "map[string]string | default={}"
      bucketName: string
      versioning: boolean | default=true
      encryption: boolean | default=true
      publicAccess: boolean | default=false
    status:
      bucketARN: ${bucket.status.ackResourceMetadata.arn}
      bucketName: ${bucket.spec.name}
      logBucketARN: ${logBucket.status.ackResourceMetadata.arn}
      logBucketName: ${logBucket.spec.name}
      readWritePolicyARN: ${rwPolicy.status.ackResourceMetadata.arn}
      readOnlyPolicyARN: ${roPolicy.status.ackResourceMetadata.arn}

  resources:
  - id: bucket
    readyWhen:
      - ${bucket.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.bucketName}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.bucketName}
        tagging:
          tagSet: |-
            ${[
              {"key": "Name", "value": "${schema.spec.bucketName}"},
              {"key": "Environment", "value": "${schema.spec.environment}"},
              {"key": "Purpose", "value": "data-storage"}
            ] + schema.spec.tags.map(k, {"key": k, "value": schema.spec.tags[k]})}

  - id: logBucket
    readyWhen:
      - ${logBucket.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.bucketName}-logs
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.bucketName}-logs
        tagging:
          tagSet: |-
            ${[
              {"key": "Name", "value": "${schema.spec.bucketName}-logs"},
              {"key": "Environment", "value": "${schema.spec.environment}"},
              {"key": "Purpose", "value": "access-logs"}
            ] + schema.spec.tags.map(k, {"key": k, "value": schema.spec.tags[k]})}

  - id: rwPolicy
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Policy
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.bucketName}-rw-policy
      spec:
        name: ${schema.spec.bucketName}-rw-policy
        description: "Read-Write access policy for ${schema.spec.bucketName}"
        policyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:GetObject",
                  "s3:PutObject",
                  "s3:PutObjectAcl",
                  "s3:DeleteObject",
                  "s3:GetObjectVersion",
                  "s3:DeleteObjectVersion"
                ],
                "Resource": [
                  "${bucket.status.ackResourceMetadata.arn}/*"
                ]
              },
              {
                "Effect": "Allow",
                "Action": [
                  "s3:ListBucket",
                  "s3:GetBucketLocation",
                  "s3:ListBucketVersions"
                ],
                "Resource": [
                  "${bucket.status.ackResourceMetadata.arn}"
                ]
              }
            ]
          }

  - id: roPolicy
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Policy
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.bucketName}-ro-policy
      spec:
        name: ${schema.spec.bucketName}-ro-policy
        description: "Read-Only access policy for ${schema.spec.bucketName}"
        policyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:GetObject",
                  "s3:GetObjectVersion"
                ],
                "Resource": [
                  "${bucket.status.ackResourceMetadata.arn}/*"
                ]
              },
              {
                "Effect": "Allow",
                "Action": [
                  "s3:ListBucket",
                  "s3:GetBucketLocation",
                  "s3:ListBucketVersions"
                ],
                "Resource": [
                  "${bucket.status.ackResourceMetadata.arn}"
                ]
              }
            ]
          }
