apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-elasticache.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsElastiCache
    spec:
      name: string
      namespace: string
      region: string | default=""
      environment: string | default="dev"
      project: string | default="kro-managed"
      vpcID: string
      subnetIDs: "[]string"
      privateSubnet1Cidr: string | default=""
      privateSubnet2Cidr: string | default=""
      privateSubnet3Cidr: string | default=""
      engine: string | default="redis"
      engineVersion: string | default="7.0"
      nodeType: string | default="cache.t3.micro"
      numCacheNodes: integer | default=1
      logging:
        enableSlowLog: boolean | default=false
        logGroupName: string | default=""
        retentionInDays: integer | default=1827
    status:
      cacheClusterARN: ${cacheCluster.status.ackResourceMetadata.arn}
      cacheClusterID: ${cacheCluster.spec.cacheClusterID}
      subnetGroupName: ${cacheSubnetGroup.spec.cacheSubnetGroupName}
      endpoint: ${cacheCluster.status.cacheNodes[0].endpoint.address}
      port: ${cacheCluster.status.cacheNodes[0].endpoint.port}
      slowLogGroupARN: ${slowLogGroup.?status.?ackResourceMetadata.?arn}

  resources:
  - id: cacheSubnetGroup
    readyWhen:
      - ${cacheSubnetGroup.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
    template:
      apiVersion: elasticache.services.k8s.aws/v1alpha1
      kind: CacheSubnetGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cache-subnet-group
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        cacheSubnetGroupName: ${schema.spec.name}-cache-subnet-group
        cacheSubnetGroupDescription: "ElastiCache subnet group"
        subnetIDs: ${schema.spec.subnetIDs}
        tags:
        - key: Name
          value: ${schema.spec.name}-cache-subnet-group
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: securityGroupSubnet1
    readyWhen:
      - ${securityGroupSubnet1.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${securityGroupSubnet1.status.id != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cache-sg-subnet1
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-cache-sg-subnet1
        description: "ElastiCache security group for private subnet 1"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 6379
            toPort: 6379
            ipProtocol: tcp
            ipRanges:
              - cidrIP: ${schema.spec.privateSubnet1Cidr}
        tags:
        - key: Name
          value: ${schema.spec.name}-cache-sg-subnet1
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: securityGroupSubnet2
    includeWhen:
      - ${schema.spec.privateSubnet2Cidr != ""}
    readyWhen:
      - ${securityGroupSubnet2.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${securityGroupSubnet2.status.id != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cache-sg-subnet2
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-cache-sg-subnet2
        description: "ElastiCache security group for private subnet 2"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 6379
            toPort: 6379
            ipProtocol: tcp
            ipRanges:
              - cidrIP: ${schema.spec.privateSubnet2Cidr}
        tags:
        - key: Name
          value: ${schema.spec.name}-cache-sg-subnet2
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: securityGroupSubnet3
    includeWhen:
      - ${schema.spec.privateSubnet3Cidr != ""}
    readyWhen:
      - ${securityGroupSubnet3.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${securityGroupSubnet3.status.id != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cache-sg-subnet3
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-cache-sg-subnet3
        description: "ElastiCache security group for private subnet 3"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 6379
            toPort: 6379
            ipProtocol: tcp
            ipRanges:
              - cidrIP: ${schema.spec.privateSubnet3Cidr}
        tags:
        - key: Name
          value: ${schema.spec.name}-cache-sg-subnet3
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: slowLogGroup
    includeWhen:
      - ${schema.spec.logging.enableSlowLog}
    readyWhen:
      - ${slowLogGroup.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${slowLogGroup.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: cloudwatchlogs.services.k8s.aws/v1alpha1
      kind: LogGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-elasticache-slow-log
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: "${ schema.spec.logging.logGroupName != \"\" ? schema.spec.logging.logGroupName : \"/aws/elasticache/\" + schema.spec.name + \"/slow-log\" }"
        retentionDays: ${schema.spec.logging.retentionInDays}
  - id: cacheCluster
    readyWhen:
      - ${cacheCluster.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${cacheCluster.status.cacheClusterStatus == "available"}
      - ${cacheCluster.status.cacheNodes[0].endpoint.address != ""}
    template:
      apiVersion: elasticache.services.k8s.aws/v1alpha1
      kind: CacheCluster
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cache
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        cacheClusterID: ${schema.spec.name}-cache
        cacheNodeType: ${schema.spec.nodeType}
        engine: ${schema.spec.engine}
        engineVersion: ${schema.spec.engineVersion}
        numCacheNodes: ${schema.spec.numCacheNodes}
        cacheSubnetGroupName: ${cacheSubnetGroup.spec.cacheSubnetGroupName}
        securityGroupIDs: "${ [securityGroupSubnet1.status.id] + (schema.spec.privateSubnet2Cidr != \"\" ? [securityGroupSubnet2.status.id] : []) + (schema.spec.privateSubnet3Cidr != \"\" ? [securityGroupSubnet3.status.id] : []) }"
        logDeliveryConfigurations: "${ schema.spec.logging.enableSlowLog ? [{\"destinationType\": \"cloudwatch-logs\", \"logFormat\": \"json\", \"logType\": \"slow-log\", \"destinationDetails\": {\"cloudWatchLogsDetails\": {\"logGroup\": slowLogGroup.spec.name}}}, {\"destinationType\": \"cloudwatch-logs\", \"logFormat\": \"json\", \"logType\": \"engine-log\", \"destinationDetails\": {\"cloudWatchLogsDetails\": {\"logGroup\": slowLogGroup.spec.name}}}] : [] }"
        tags:
        - key: Name
          value: ${schema.spec.name}-cache
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
