apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-elasticache.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsElastiCache
    spec:
      name: string
      namespace: string
      overrideRegion: string | default=""
      environment: string | default="dev"
      tags: "map[string]string | default={}"
      vpcID: string
      subnetIDs: "[]string"
      ingressIPRanges: "[]string | default=[\"10.0.0.0/8\"]"
      engine: string | default="redis"
      engineVersion: string | default="7.0"
      nodeType: string | default="cache.t3.micro"
      numCacheNodes: integer | default=1
    status:
      cacheClusterARN: ${cacheCluster.status.ackResourceMetadata.arn}
      cacheClusterID: ${cacheCluster.spec.cacheClusterID}
      subnetGroupName: ${cacheSubnetGroup.spec.cacheSubnetGroupName}
      endpoint: ${cacheCluster.status.configurationEndpoint.address}
      port: ${cacheCluster.status.configurationEndpoint.port}

  resources:
  - id: cacheSubnetGroup
    readyWhen:
      - ${cacheSubnetGroup.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: elasticache.services.k8s.aws/v1alpha1
      kind: CacheSubnetGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cache-subnet-group
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        cacheSubnetGroupName: ${schema.spec.name}-cache-subnet-group
        cacheSubnetGroupDescription: "ElastiCache subnet group"
        subnetIDs: ${schema.spec.subnetIDs}
        tags:
          - key: "Name"
            value: ${schema.spec.name}-cache-subnet-group
          - key: "Environment"
            value: ${schema.spec.environment}
  - id: securityGroup
    readyWhen:
      - ${securityGroup.status.id != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cache-sg
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        name: ${schema.spec.name}-cache-sg
        description: "ElastiCache security group"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 6379
            toPort: 6379
            ipProtocol: tcp
            ipRanges: "${schema.spec.ingressIPRanges.map(ip, {\"cidrIP\": ip})}"
        tags:
          - key: "Name"
            value: ${schema.spec.name}-cache-sg
          - key: "Environment"
            value: ${schema.spec.environment}
  - id: cacheCluster
    readyWhen:
      - ${cacheCluster.status.cacheClusterStatus == "available"}
    template:
      apiVersion: elasticache.services.k8s.aws/v1alpha1
      kind: CacheCluster
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cache
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        cacheClusterID: ${schema.spec.name}-cache
        cacheNodeType: ${schema.spec.nodeType}
        engine: ${schema.spec.engine}
        engineVersion: ${schema.spec.engineVersion}
        numCacheNodes: ${schema.spec.numCacheNodes}
        cacheSubnetGroupName: ${cacheSubnetGroup.spec.cacheSubnetGroupName}
        securityGroupIDs:
          - ${securityGroup.status.id}
        tags:
          - key: "Name"
            value: ${schema.spec.name}-cache
          - key: "Environment"
            value: ${schema.spec.environment}
