apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-kms.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsKMS
    spec:
      name: string
      namespace: string
      region: string | default=""
      environment: string | default="dev"
      project: string | default="kro-managed"
      description: string | default="KMS encryption key"
      keyUsage: string | default="ENCRYPT_DECRYPT"
      customerMasterKeySpec: string | default="SYMMETRIC_DEFAULT"
      multiRegion: boolean | default=false
      enableKeyRotation: boolean | default=true
    status:
      keyARN: ${key.status.ackResourceMetadata.arn}
      keyID: ${key.status.keyID}
      aliasARN: ${alias.status.ackResourceMetadata.arn}

  resources:
  - id: key
    template:
      apiVersion: kms.services.k8s.aws/v1alpha1
      kind: Key
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        description: ${schema.spec.description}
        keyUsage: ${schema.spec.keyUsage}
        keySpec: ${schema.spec.customerMasterKeySpec}
        multiRegion: ${schema.spec.multiRegion}
        tags:
        - tagKey: Name
          tagValue: ${schema.spec.name}
        - tagKey: Environment
          tagValue: ${schema.spec.environment}
        - tagKey: ManagedBy
          tagValue: Kro
        - tagKey: Project
          tagValue: ${schema.spec.project}
  - id: alias
    template:
      apiVersion: kms.services.k8s.aws/v1alpha1
      kind: Alias
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-alias
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: alias/${schema.spec.name}
        targetKeyID: ${key.status.keyID}
