apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: opensearch.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsOpenSearch
    spec:
      name: string
      namespace: string
      overrideRegion: string | default=""
      environment: string | default="dev"
      tags: "map[string]string | default={}"
      vpcID: string
      subnetIDs: "[]string"
      ingressCIDRs: "[]string | default=[\"10.0.0.0/8\"]"
      engineVersion: string | default="OpenSearch_2.11"
      instanceType: string | default="t3.small.search"
      instanceCount: integer | default=1
      volumeSize: integer | default=10
    status:
      domainARN: ${domain.status.ackResourceMetadata.arn}
      domainName: ${domain.spec.name}
      endpoint: ${domain.status.endpoint}

  resources:
  - id: securityGroup
    readyWhen:
      - ${securityGroup.status.id != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-opensearch-sg
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        name: ${schema.spec.name}-opensearch-sg
        description: "OpenSearch security group"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 443
            toPort: 443
            ipProtocol: tcp
            ipRanges: "${ schema.spec.ingressCIDRs.map(c, {cidrIP: c}) }"
        tags:
          - key: "Name"
            value: ${schema.spec.name}-opensearch-sg
          - key: "Environment"
            value: ${schema.spec.environment}
  - id: domain
    readyWhen:
      - ${domain.status.processing == false}
    template:
      apiVersion: opensearchservice.services.k8s.aws/v1alpha1
      kind: Domain
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-opensearch
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        name: ${schema.spec.name}-opensearch
        engineVersion: ${schema.spec.engineVersion}
        clusterConfig:
          instanceType: ${schema.spec.instanceType}
          instanceCount: ${schema.spec.instanceCount}
          dedicatedMasterEnabled: false
          zoneAwarenessEnabled: false
        ebsOptions:
          ebsEnabled: true
          volumeSize: ${schema.spec.volumeSize}
          volumeType: gp3
        vpcOptions:
          subnetIDs: ${schema.spec.subnetIDs}
          securityGroupIDs:
            - ${securityGroup.status.id}
        encryptionAtRestOptions:
          enabled: true
        nodeToNodeEncryptionOptions:
          enabled: true
        domainEndpointOptions:
          enforceHTTPS: true
          tlsSecurityPolicy: Policy-Min-TLS-1-2-2019-07
        tags:
          - key: "Name"
            value: ${schema.spec.name}-opensearch
          - key: "Environment"
            value: ${schema.spec.environment}
