apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-opensearch.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsOpenSearch
    spec:
      name: string
      namespace: string
      region: string | default=""
      environment: string | default="dev"
      project: string | default="kro-managed"
      vpcID: string
      subnetIDs: "[]string"
      privateSubnet1Cidr: string | default=""
      privateSubnet2Cidr: string | default=""
      privateSubnet3Cidr: string | default=""
      engineVersion: string | default="OpenSearch_2.11"
      instanceType: string | default="t3.small.search"
      instanceCount: integer | default=1
      volumeSize: integer | default=10
      dedicatedMasterEnabled: boolean | default=false
      zoneAwarenessEnabled: boolean | default=false
      logging:
        enableAuditLogs: boolean | default=false
        enableErrorLogs: boolean | default=false
        enableIndexSlowLogs: boolean | default=false
        enableSearchSlowLogs: boolean | default=false
        retentionInDays: integer | default=1827
    status:
      domainARN: ${domain.status.ackResourceMetadata.arn}
      domainName: ${domain.spec.name}
      endpoint: ${domain.status.endpoints.vpc}
      auditLogGroupARN: ${auditLogGroup.?status.?ackResourceMetadata.?arn}
      errorLogGroupARN: ${errorLogGroup.?status.?ackResourceMetadata.?arn}
      indexSlowLogGroupARN: ${indexSlowLogGroup.?status.?ackResourceMetadata.?arn}
      searchSlowLogGroupARN: ${searchSlowLogGroup.?status.?ackResourceMetadata.?arn}

  resources:
  - id: securityGroupSubnet1
    readyWhen:
      - ${securityGroupSubnet1.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${securityGroupSubnet1.status.id != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-sg-subnet1
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-sg-subnet1
        description: "OpenSearch security group for private subnet 1"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 443
            toPort: 443
            ipProtocol: tcp
            ipRanges:
              - cidrIP: ${schema.spec.privateSubnet1Cidr}
        tags:
        - key: Name
          value: ${schema.spec.name}-sg-subnet1
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: securityGroupSubnet2
    includeWhen:
      - ${schema.spec.privateSubnet2Cidr != ""}
    readyWhen:
      - ${securityGroupSubnet2.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${securityGroupSubnet2.status.id != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-sg-subnet2
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-sg-subnet2
        description: "OpenSearch security group for private subnet 2"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 443
            toPort: 443
            ipProtocol: tcp
            ipRanges:
              - cidrIP: ${schema.spec.privateSubnet2Cidr}
        tags:
        - key: Name
          value: ${schema.spec.name}-sg-subnet2
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: securityGroupSubnet3
    includeWhen:
      - ${schema.spec.privateSubnet3Cidr != ""}
    readyWhen:
      - ${securityGroupSubnet3.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${securityGroupSubnet3.status.id != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-sg-subnet3
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-sg-subnet3
        description: "OpenSearch security group for private subnet 3"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 443
            toPort: 443
            ipProtocol: tcp
            ipRanges:
              - cidrIP: ${schema.spec.privateSubnet3Cidr}
        tags:
        - key: Name
          value: ${schema.spec.name}-sg-subnet3
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: auditLogGroup
    includeWhen:
      - ${schema.spec.logging.enableAuditLogs}
    readyWhen:
      - ${auditLogGroup.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${auditLogGroup.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: cloudwatchlogs.services.k8s.aws/v1alpha1
      kind: LogGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-audit-log
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: /aws/opensearch/${schema.spec.name}/audit-log
        retentionDays: ${schema.spec.logging.retentionInDays}
  - id: errorLogGroup
    includeWhen:
      - ${schema.spec.logging.enableErrorLogs}
    readyWhen:
      - ${errorLogGroup.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${errorLogGroup.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: cloudwatchlogs.services.k8s.aws/v1alpha1
      kind: LogGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-error-log
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: /aws/opensearch/${schema.spec.name}/error-log
        retentionDays: ${schema.spec.logging.retentionInDays}
  - id: indexSlowLogGroup
    includeWhen:
      - ${schema.spec.logging.enableIndexSlowLogs}
    readyWhen:
      - ${indexSlowLogGroup.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${indexSlowLogGroup.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: cloudwatchlogs.services.k8s.aws/v1alpha1
      kind: LogGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-index-slow-log
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: /aws/opensearch/${schema.spec.name}/index-slow-log
        retentionDays: ${schema.spec.logging.retentionInDays}
  - id: searchSlowLogGroup
    includeWhen:
      - ${schema.spec.logging.enableSearchSlowLogs}
    readyWhen:
      - ${searchSlowLogGroup.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${searchSlowLogGroup.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: cloudwatchlogs.services.k8s.aws/v1alpha1
      kind: LogGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-search-slow-log
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: /aws/opensearch/${schema.spec.name}/search-slow-log
        retentionDays: ${schema.spec.logging.retentionInDays}
  - id: domain
    readyWhen:
      - ${domain.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${domain.status.endpoints.vpc != ""}
    template:
      apiVersion: opensearchservice.services.k8s.aws/v1alpha1
      kind: Domain
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-domain
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-domain
        engineVersion: ${schema.spec.engineVersion}
        clusterConfig:
          instanceType: ${schema.spec.instanceType}
          instanceCount: ${schema.spec.instanceCount}
          dedicatedMasterEnabled: ${schema.spec.dedicatedMasterEnabled}
          zoneAwarenessEnabled: ${schema.spec.zoneAwarenessEnabled}
        ebsOptions:
          ebsEnabled: true
          volumeSize: ${schema.spec.volumeSize}
          volumeType: gp3
        vpcOptions:
          subnetIDs: ${schema.spec.subnetIDs}
          securityGroupIDs: "${ [securityGroupSubnet1.status.id] + (schema.spec.privateSubnet2Cidr != \"\" ? [securityGroupSubnet2.status.id] : []) + (schema.spec.privateSubnet3Cidr != \"\" ? [securityGroupSubnet3.status.id] : []) }"
        encryptionAtRestOptions:
          enabled: true
        nodeToNodeEncryptionOptions:
          enabled: true
        domainEndpointOptions:
          enforceHTTPS: true
          tlsSecurityPolicy: Policy-Min-TLS-1-2-2019-07
        logPublishingOptions:
          AUDIT_LOGS:
            enabled: ${schema.spec.logging.enableAuditLogs}
            cloudWatchLogsLogGroupARN: "${ schema.spec.logging.enableAuditLogs ? auditLogGroup.status.ackResourceMetadata.arn : \"arn:aws:logs:us-east-1:111122223333:log-group:/ack/opensearch/audit\" }"
          ES_APPLICATION_LOGS:
            enabled: ${schema.spec.logging.enableErrorLogs}
            cloudWatchLogsLogGroupARN: "${ schema.spec.logging.enableErrorLogs ? errorLogGroup.status.ackResourceMetadata.arn : \"arn:aws:logs:us-east-1:111122223333:log-group:/ack/opensearch/error\" }"
          INDEX_SLOW_LOGS:
            enabled: ${schema.spec.logging.enableIndexSlowLogs}
            cloudWatchLogsLogGroupARN: "${ schema.spec.logging.enableIndexSlowLogs ? indexSlowLogGroup.status.ackResourceMetadata.arn : \"arn:aws:logs:us-east-1:111122223333:log-group:/ack/opensearch/index-slow\" }"
          SEARCH_SLOW_LOGS:
            enabled: ${schema.spec.logging.enableSearchSlowLogs}
            cloudWatchLogsLogGroupARN: "${ schema.spec.logging.enableSearchSlowLogs ? searchSlowLogGroup.status.ackResourceMetadata.arn : \"arn:aws:logs:us-east-1:111122223333:log-group:/ack/opensearch/search-slow\" }"
        tags:
        - key: Name
          value: ${schema.spec.name}-domain
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
