apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-rds.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsRDS
    spec:
      name: string
      namespace: string
      region: string | default=""
      environment: string | default="dev"
      project: string | default="kro-managed"
      vpcID: string
      subnetIDs: "[]string"
      dbSubnet1Cidr: string | default=""
      dbSubnet2Cidr: string | default=""
      engine: string | default="postgres"
      engineVersion: string | default="15.4"
      instanceClass: string | default="db.t3.medium"
      allocatedStorage: integer | default=20
      databaseName: string
      logging:
        enableCloudWatchLogs: boolean | default=false
        logTypes: "[]string | default=[\"postgresql\", \"upgrade\"]"
      monitoring:
        enableEnhancedMonitoring: boolean | default=false
        monitoringInterval: integer | default=60
    status:
      dbInstanceARN: "${ has(dbInstanceWithMonitoring.status.ackResourceMetadata.arn) ? dbInstanceWithMonitoring.status.ackResourceMetadata.arn : dbInstanceWithoutMonitoring.status.ackResourceMetadata.arn }"
      dbInstanceID: "${ has(dbInstanceWithMonitoring.spec.dbInstanceIdentifier) ? dbInstanceWithMonitoring.spec.dbInstanceIdentifier : dbInstanceWithoutMonitoring.spec.dbInstanceIdentifier }"
      endpoint: "${ has(dbInstanceWithMonitoring.status.endpoint.address) ? dbInstanceWithMonitoring.status.endpoint.address : dbInstanceWithoutMonitoring.status.endpoint.address }"
      port: "${ has(dbInstanceWithMonitoring.status.endpoint.port) ? dbInstanceWithMonitoring.status.endpoint.port : dbInstanceWithoutMonitoring.status.endpoint.port }"
      subnetGroupName: ${dbSubnetGroup.spec.name}
      monitoringRoleARN: ${monitoringRole.?status.?ackResourceMetadata.?arn}

  resources:
  - id: dbSubnetGroup
    readyWhen:
      - ${dbSubnetGroup.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
    template:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBSubnetGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-db-subnet-group
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-db-subnet-group
        description: "RDS subnet group"
        subnetIDs: ${schema.spec.subnetIDs}
        tags:
        - key: Name
          value: ${schema.spec.name}-db-subnet-group
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: securityGroup
    readyWhen:
      - ${securityGroup.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${securityGroup.status.id != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: SecurityGroup
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-db-sg
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-db-sg
        description: "RDS security group"
        vpcID: ${schema.spec.vpcID}
        ingressRules:
          - fromPort: 5432
            toPort: 5432
            ipProtocol: tcp
            ipRanges:
              - cidrIP: ${schema.spec.dbSubnet1Cidr}
              - cidrIP: ${schema.spec.dbSubnet2Cidr}
        tags:
        - key: Name
          value: ${schema.spec.name}-db-sg
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  - id: monitoringRole
    includeWhen:
      - ${schema.spec.monitoring.enableEnhancedMonitoring}
    readyWhen:
      - ${monitoringRole.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${monitoringRole.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-monitoring-role
        annotations:
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-monitoring-role
        description: "RDS enhanced monitoring IAM role"
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "monitoring.rds.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }
        policies:
          - "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
        tags:
          - key: "Name"
            value: "${schema.spec.name}-monitoring-role"
          - key: "Environment"
            value: "${schema.spec.environment}"
          - key: "ManagedBy"
            value: "Kro"
  # RDS Instance without enhanced monitoring
  - id: dbInstanceWithoutMonitoring
    includeWhen:
      - ${!schema.spec.monitoring.enableEnhancedMonitoring}
    readyWhen:
      - ${dbInstanceWithoutMonitoring.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${dbInstanceWithoutMonitoring.status.dbInstanceStatus == "available"}
      - ${dbInstance.status.endpoint.address != ""}
    template:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBInstance
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-db
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        dbInstanceIdentifier: ${schema.spec.name}-instance
        dbInstanceClass: ${schema.spec.instanceClass}
        engine: ${schema.spec.engine}
        engineVersion: ${schema.spec.engineVersion}
        allocatedStorage: ${schema.spec.allocatedStorage}
        dbName: ${schema.spec.databaseName}
        masterUsername: "admin"
        manageMasterUserPassword: true
        dbSubnetGroupName: ${dbSubnetGroup.spec.name}
        vpcSecurityGroupIDs:
          - ${securityGroup.status.id}
        publiclyAccessible: false
        storageEncrypted: true
        enableCloudwatchLogsExports: "${ schema.spec.logging.enableCloudWatchLogs ? schema.spec.logging.logTypes : [] }"
        monitoringInterval: 0
        tags:
        - key: Name
          value: ${schema.spec.name}-instance
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
  # PostgreSQL RDS instance with enhanced monitoring
  - id: dbInstanceWithMonitoring
    includeWhen:
      - ${schema.spec.monitoring.enableEnhancedMonitoring}
    readyWhen:
      - ${dbInstance.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
      - ${dbInstance.status.dbInstanceStatus == "available"}
      - ${dbInstance.status.endpoint.address != ""}
    template:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBInstance
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-db
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        dbInstanceIdentifier: ${schema.spec.name}-instance
        dbInstanceClass: ${schema.spec.instanceClass}
        engine: ${schema.spec.engine}
        engineVersion: ${schema.spec.engineVersion}
        allocatedStorage: ${schema.spec.allocatedStorage}
        dbName: ${schema.spec.databaseName}
        masterUsername: "admin"
        manageMasterUserPassword: true
        dbSubnetGroupName: ${dbSubnetGroup.spec.name}
        vpcSecurityGroupIDs:
          - ${securityGroup.status.id}
        publiclyAccessible: false
        storageEncrypted: true
        enableCloudwatchLogsExports: "${ schema.spec.logging.enableCloudWatchLogs ? schema.spec.logging.logTypes : [] }"
        monitoringInterval: ${schema.spec.monitoring.monitoringInterval}
        monitoringRoleARN: ${monitoringRole.status.ackResourceMetadata.arn}
        tags:
        - key: Name
          value: ${schema.spec.name}-instance
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
