apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-route53-private.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsRoute53Private
    spec:
      name: string
      namespace: string
      region: string | default="us-east-1"
      environment: string | default="dev"
      tags: "map[string]string | default={}"
      zoneName: string
      vpcID: string | default=""
      comment: string | default="Hosted zone"
    status:
      hostedZoneID: ${hostedZone.status.id}
      hostedZoneARN: ${hostedZone.status.ackResourceMetadata.arn}
      nameServers: ${hostedZone.status.delegationSet.nameServers}

  resources:
  - id: hostedZone
    readyWhen:
      - ${hostedZone.status.id != ""}
    template:
      apiVersion: route53.services.k8s.aws/v1alpha1
      kind: HostedZone
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.zoneName}
        hostedZoneConfig:
          comment: ${schema.spec.comment}
          privateZone: true
        vpc:
          vpcID: ${schema.spec.vpcID}
          vpcRegion: ${schema.spec.region}
        tags: |-
          ${[
            {"key": "Name", "value": "${schema.spec.name}"},
            {"key": "Environment", "value": "${schema.spec.environment}"}
          ] + schema.spec.tags.map(k, {"key": k, "value": schema.spec.tags[k]})}
