apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-route53-public.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsRoute53Public
    spec:
      name: string
      namespace: string
      region: string | default="us-east-1"
      environment: string | default="dev"
      project: string | default="kro-managed"
      zoneName: string
      vpcID: string | default=""
      comment: string | default="Hosted zone"
    status:
      hostedZoneID: ${hostedZone.status.id}
      hostedZoneARN: ${hostedZone.status.ackResourceMetadata.arn}
      nameServers: ${hostedZone.status.delegationSet.nameServers}

  resources:
  - id: hostedZone
    template:
      apiVersion: route53.services.k8s.aws/v1alpha1
      kind: HostedZone
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.zoneName}
        hostedZoneConfig:
          comment: ${schema.spec.comment}
          privateZone: false
        tags:
        - key: Name
          value: ${schema.spec.name}
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
