apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-s3bucket.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsS3Bucket
    spec:
      name: string
      namespace: string
      region: string | default=""
      environment: string | default="dev"
      project: string | default="kro-managed"
      access: string | default="write"
      versioning: boolean | default=true
      encryption: boolean | default=true
      kmsKeyARN: string | default=""
    status:
      s3ARN: ${s3bucket.status.ackResourceMetadata.arn}
      s3Name: ${s3bucket.spec.name}
      s3PolicyARN: ${s3Policy.status.ackResourceMetadata.arn}

  resources:
  - id: s3bucket
    readyWhen:
      - ${s3bucket.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
    template:
      apiVersion: s3.services.k8s.aws/v1alpha1
      kind: Bucket
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}
        encryption:
          rules:
          - applyServerSideEncryptionByDefault:
              sseAlgorithm: "${ schema.spec.kmsKeyARN != \"\" ? \"aws:kms\" : \"AES256\" }"
              kmsMasterKeyID: ${schema.spec.kmsKeyARN}
            bucketKeyEnabled: true
        tagging:
          tagSet:
          - key: Name
            value: ${schema.spec.name}
          - key: Environment
            value: ${schema.spec.environment}
  - id: s3Policy
    readyWhen:
      - ${s3Policy.status.conditions.exists(c, c.type == "ACK.ResourceSynced" && c.status == "True")}
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Policy
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-s3-policy
        annotations:
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        name: ${schema.spec.name}-s3-policy
        policyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:GetObject",
                  "s3:PutObject",
                  "s3:PutObjectAcl",
                  "s3:DeleteObject"
                ],
                "Resource": [
                  "${s3bucket.status.ackResourceMetadata.arn}/*"
                ]
              },
              {
                "Effect": "Allow",
                "Action": [
                  "s3:ListBucket",
                  "s3:GetBucketLocation"
                ],
                "Resource": [
                  "${s3bucket.status.ackResourceMetadata.arn}"
                ]
              }
            ]
          }
