apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-secretsmanager.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsSecretsManager
    spec:
      name: string
      namespace: string
      overrideRegion: string | default=""
      environment: string | default="dev"
      tags: "map[string]string | default={}"
      description: string | default="Secret"
      kmsKeyID: string | default=""
      secretString: string | default=""
    status:
      secretARN: ${secret.status.ackResourceMetadata.arn}
      secretName: ${secret.spec.name}

  resources:
  - id: secret
    readyWhen:
      - ${secret.status.ackResourceMetadata.arn != ""}
    template:
      apiVersion: secretsmanager.services.k8s.aws/v1alpha1
      kind: Secret
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.overrideRegion}
      spec:
        name: ${schema.spec.name}
        description: ${schema.spec.description}
        kmsKeyID: ${schema.spec.kmsKeyID}
        secretString: ${schema.spec.secretString}
        tags:
          - key: "Name"
            value: ${schema.spec.name}
          - key: "Environment"
            value: ${schema.spec.environment}
