apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: sns.kro.run
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-4"
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsSNS
    spec:
      name: string
      namespace: string
      region: string
      environment: string | default="dev"
      tags: "map[string]string | default={}"
      displayName: string | default=""
    status:
      topicARN: ${topic.status.ackResourceMetadata.arn}
      topicName: ${topic.spec.name}

  resources:
  - id: topic
    template:
      apiVersion: sns.services.k8s.aws/v1alpha1
      kind: Topic
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        name: ${schema.spec.name}
        displayName: ${schema.spec.displayName}
        tags:
          - key: "Name"
            value: ${schema.spec.name}
          - key: "Environment"
            value: ${schema.spec.environment}
