apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-vpc.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsVpc
    spec:
      name: string
      namespace: string
      region: string | default="us-east-1"
      environment: string | default="dev"
      project: string | default="kro-managed"
      cidr:
        vpcCidr: string | default="10.0.0.0/16"
        publicSubnetCidr: string | default="10.0.1.0/24"
        privateSubnetCidr: string | default="10.0.11.0/24"
    status:
      vpcID: ${vpc.status.vpcID}
      publicSubnetID: ${publicSubnet.status.subnetID}
      privateSubnetID: ${privateSubnet.status.subnetID}
      internetGatewayID: ${internetGateway.status.internetGatewayID}
      natGatewayID: ${natGateway.status.natGatewayID}
      publicRouteTableID: ${publicRoutetable.status.routeTableID}
      privateRouteTableID: ${privateRoutetable.status.routeTableID}
  resources:
  - id: vpc
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: VPC
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-vpc
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        cidrBlocks:
        - ${schema.spec.cidr.vpcCidr}
        enableDNSSupport: true
        enableDNSHostnames: true
        tags:
        - key: Name
          value: ${schema.spec.name}-vpc
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}

  - id: internetGateway
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: InternetGateway
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-igw
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        vpc: ${vpc.status.vpcID}
        tags:
        - key: Name
          value: ${schema.spec.name}-igw
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}

  - id: eip
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: ElasticIPAddress
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-1-eip
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        tags:
        - key: Name
          value: ${schema.spec.name}-1-eip
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}

  - id: natGateway
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: NATGateway
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-1-nat-gateway
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        subnetID: ${publicSubnet.status.subnetID}
        allocationID: ${eip.status.allocationID}
        tags:
        - key: Name
          value: ${schema.spec.name}-1-nat-gateway
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}

  - id: publicRoutetable
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: RouteTable
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-1-public-routetable
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        vpcID: ${vpc.status.vpcID}
        routes:
        - destinationCIDRBlock: 0.0.0.0/0
          gatewayID: ${internetGateway.status.internetGatewayID}
        tags:
        - key: Name
          value: ${schema.spec.name}-1-public-routetable
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}

  - id: privateRoutetable
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: RouteTable
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-1-private-routetable
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        vpcID: ${vpc.status.vpcID}
        routes:
        - destinationCIDRBlock: 0.0.0.0/0
          natGatewayID: ${natGateway.status.natGatewayID}
        tags:
        - key: Name
          value: ${schema.spec.name}-1-private-routetable
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}

  - id: publicSubnet
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: Subnet
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-1-public-subnet
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        availabilityZone: ${schema.spec.region}a
        cidrBlock: ${schema.spec.cidr.publicSubnetCidr}
        mapPublicIPOnLaunch: true
        vpcID: ${vpc.status.vpcID}
        routeTables:
        - ${publicRoutetable.status.routeTableID}
        tags:
        - key: Name
          value: ${schema.spec.name}-1-public-subnet
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
        - key: kubernetes.io/role/elb
          value: "1"

  - id: privateSubnet
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: Subnet
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-1-private-subnet
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
          services.k8s.aws/adoption-policy: "adopt-or-create"
      spec:
        availabilityZone: ${schema.spec.region}a
        cidrBlock: ${schema.spec.cidr.privateSubnetCidr}
        vpcID: ${vpc.status.vpcID}
        routeTables:
        - ${privateRoutetable.status.routeTableID}
        tags:
        - key: Name
          value: ${schema.spec.name}-1-private-subnet
        - key: Environment
          value: ${schema.spec.environment}
        - key: ManagedBy
          value: Kro
        - key: Project
          value: ${schema.spec.project}
        - key: kubernetes.io/role/internal-elb
          value: "1"
