apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: aws-vpc-public-subnet.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: AwsVpcPublicSubnet
    spec:
      name: string
      namespace: string
      region: string | default="us-east-1"
      environment: string | default="dev"
      tags: "map[string]string | default={}"
      # Subnet configuration
      availabilityZone: string  # e.g., "us-east-1a"
      cidrBlock: string
      # External references
      vpcID: string
      internetGatewayID: string

    status:
      subnetID: ${publicSubnet.status.subnetID}
      publicRouteTableID: ${publicRoutetable.status.routeTableID}

  resources:
  - id: publicRoutetable
    readyWhen:
      - ${publicRoutetable.status.routeTableID != ""}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: RouteTable
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-public-routetable
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        vpcID: ${schema.spec.vpcID}
        routes:
        - destinationCIDRBlock: 0.0.0.0/0
          gatewayID: ${schema.spec.internetGatewayID}
        tags: |-
          ${[
            {"key": "Name", "value": "${schema.spec.name}-public-routetable"},
            {"key": "Environment", "value": "${schema.spec.environment}"}
          ] + schema.spec.tags.map(k, {"key": k, "value": schema.spec.tags[k]})}

  - id: publicSubnet
    readyWhen:
      - ${publicSubnet.status.state == "available"}
    template:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: Subnet
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-public-subnet
        annotations:
          services.k8s.aws/region: ${schema.spec.region}
      spec:
        availabilityZone: ${schema.spec.availabilityZone}
        cidrBlock: ${schema.spec.cidrBlock}
        mapPublicIPOnLaunch: true
        vpcID: ${schema.spec.vpcID}
        routeTables:
        - ${publicRoutetable.status.routeTableID}
        tags: |-
          ${[
            {"key": "Name", "value": "${schema.spec.name}-public-subnet"},
            {"key": "Environment", "value": "${schema.spec.environment}"},
            {"key": "kubernetes.io/role/elb", "value": "1"}
          ] + schema.spec.tags.map(k, {"key": k, "value": schema.spec.tags[k]})}
