apiVersion: kro.run/v1alpha1
kind: Gen3GKE
metadata:
  name: gen3gke
  namespace: default
spec:
  name: gen3-gcp-base
  project: my-gcp-project
  region: us-central1
  vpcName: gen3-gcp-base-vpc
  subnetName: gen3-gcp-base-subnet
  kubernetesVersion: "1.31"
  initialNodeCount: 2
  machineType: "e2-medium"
  minNodeCount: 1
  maxNodeCount: 4
