---
# Per-Controller ACK Cross-Account Role ConfigMap Template
#
# This ConfigMap is deployed per ACK controller into the ack-system namespace
# It tells each ACK controller which IAM role to assume for each AWS account
#
# Usage: ACK controllers read this ConfigMap to find the IAM role ARN per account
# The key is the AWS account ID (e.g., "111111111111")
# The value is the IAM role ARN for that controller in that account
#
# Example ConfigMap for S3 controller:
#   name: spoke1-ack-s3-crossaccount-role-map
#   namespace: ack-system
#   data:
#     "111111111111": arn:aws:iam::111111111111:role/spoke1-ack-s3-spoke-role
#     "222222222222": arn:aws:iam::222222222222:role/spoke2-ack-s3-spoke-role
apiVersion: v1
kind: ConfigMap
metadata:
  name: <spoke_alias>-<controller_name>-crossaccount-role-map
  namespace: ack-system
  labels:
    app.kubernetes.io/name: <spoke_alias>-<controller_name>-crossaccount-role-map
    app.kubernetes.io/part-of: gen3-kro
    app.kubernetes.io/component: ack-controller
    app.kubernetes.io/controller: <controller_name>
data:
  # Format: "account-id": role-arn
  # Example for S3 controller:
  # "111111111111": arn:aws:iam::111111111111:role/spoke1-ack-s3-spoke-role
  # "222222222222": arn:aws:iam::222222222222:role/spoke2-ack-s3-spoke-role
---
# Spoke Infrastructure Namespace with Account Annotation
#
# Each spoke infrastructure namespace is annotated with the owner account ID
# This allows ACK controllers to identify which account owns resources in this namespace
apiVersion: v1
kind: Namespace
metadata:
  name: <spoke_alias>-infrastructure
  annotations:
    services.k8s.aws/owner-account-id: "<account_id>"
  labels:
    app.kubernetes.io/name: <spoke_alias>-infrastructure
    app.kubernetes.io/part-of: gen3-kro
    app.kubernetes.io/managed-by: terraform
    gen3.io/spoke: <spoke_alias>

