# Spoke Infrastructure Namespace Template
# This template is processed by ArgoCD ApplicationSet with values from spokes-charter.yaml
# Each spoke gets its own namespace with account ID annotation for ACK controllers
---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{.spoke.alias}}-{{.spoke.namespace_suffix}}"
  annotations:
    # AWS account ID for cross-account resource management
    services.k8s.aws/owner-account-id: "{{.spoke.account_id}}"
    # Spoke metadata
    gen3.io/spoke-alias: "{{.spoke.alias}}"
    gen3.io/spoke-environment: "{{.spoke.environment}}"
    gen3.io/spoke-region: "{{.spoke.region}}"
  labels:
    app.kubernetes.io/name: "{{.spoke.alias}}-infrastructure"
    app.kubernetes.io/part-of: gen3-kro
    app.kubernetes.io/managed-by: argocd
    gen3.io/spoke: "{{.spoke.alias}}"
    gen3.io/environment: "{{.spoke.environment}}"
    gen3.io/namespace-type: infrastructure
