apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vpc-core-t1-rgd.yaml
  - vpc-subnets-db-t1-rgd.yaml
  - vpc-subnets-private-t1-rgd.yaml
  - vpc-subnets-public-t1-rgd.yaml
  - vpc-routetable-db-t1-rgd.yaml
  - vpc-routetable-public-t1-rgd.yaml
  - vpc-routetables-private-t1-rgd.yaml
  - vpc-natgateways-t1-rgd.yaml
