apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ack-ec2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
        matchExpressions:
          - key: enable_ack_ec2
            operator: In
            values: ['true']
  template:
    metadata:
      name: '{{.name}}-ack-ec2'
      labels:
        app: ack-ec2
        cluster: '{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: public.ecr.aws
        chart: aws-controllers-k8s/ec2-chart
        targetRevision: v1.3.4
        helm:
          releaseName: ack-ec2-controller
          values: |
            aws:
              region: {{if eq .metadata.labels.fleet_member "control-plane"}}{{.metadata.annotations.hub_aws_region}}{{else}}{{.metadata.annotations.aws_region}}{{end}}
            serviceAccount:
              name: ack-ec2-controller
              annotations:
                eks.amazonaws.com/role-arn: {{if eq .metadata.labels.fleet_member "control-plane"}}{{index .metadata.annotations "gen3-csoc-ec2-ack-arn"}}{{else}}{{index .metadata.annotations (printf "%s-ec2-ack-arn" .name)}}{{end}}
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
      destination:
        server: '{{.server}}'
        namespace: ack-system
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 10m
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
