apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: calico-cleanup
spec:
  disruption:
    budgets:
      - nodes: 100%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
  limits:
    cpu: "4"
    memory: 16Gi
  template:
    metadata:
      labels:
        role: default
    spec:
      expireAfter: 2h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      terminationGracePeriod: 1h
  weight: 1
