apiVersion: kro.run/v1alpha1
kind: Gen3IRSARole
metadata:
  name: gen3fenceirsa
  namespace: default
spec:
  name: gen3-base
  region: us-east-1
  clusterName: gen3-base
  namespace: default
  serviceAccountName: fence
  policyARNs: []
