apiVersion: kro.run/v1alpha1
kind: Gen3OpenSearch
metadata:
  name: gen3opensearch
  namespace: default
spec:
  name: gen3-base
  region: us-east-1
  domainName: gen3-base
  version: "2.9"
  instanceType: "t3.medium.search"
  instanceCount: 2
  volumeSize: 100
  vpcID: ""  # Populated by overlay
  subnetIDs: []  # Populated by overlay
