apiVersion: kro.run/v1alpha1
kind: Gen3SecretsManager
metadata:
  name: gen3secrets
  namespace: default
spec:
  name: gen3-base
  region: us-east-1
  secretName: gen3-base-secrets
  description: "Gen3 application secrets"
