# CRD Catalog Configuration
# Defines the repository path for each controller's CRDs
# Used by csoc-crds-appset to deploy CRD bundles

- controller: kro
  path: argocd/csoc-addons/crds/kro
  sync_wave: "-30"

- controller: ack-cloudtrail
  path: argocd/csoc-addons/crds/ack-cloudtrail
  sync_wave: "-30"

- controller: ack-cloudwatchlogs
  path: argocd/csoc-addons/crds/ack-cloudwatchlogs
  sync_wave: "-30"

- controller: ack-ec2
  path: argocd/csoc-addons/crds/ack-ec2
  sync_wave: "-30"

- controller: ack-efs
  path: argocd/csoc-addons/crds/ack-efs
  sync_wave: "-30"

- controller: ack-eks
  path: argocd/csoc-addons/crds/ack-eks
  sync_wave: "-30"

- controller: ack-elasticache
  path: argocd/csoc-addons/crds/ack-elasticache
  sync_wave: "-30"

- controller: ack-iam
  path: argocd/csoc-addons/crds/ack-iam
  sync_wave: "-30"

- controller: ack-kms
  path: argocd/csoc-addons/crds/ack-kms
  sync_wave: "-30"

- controller: ack-opensearchservice
  path: argocd/csoc-addons/crds/ack-opensearchservice
  sync_wave: "-30"

- controller: ack-rds
  path: argocd/csoc-addons/crds/ack-rds
  sync_wave: "-30"

- controller: ack-route53
  path: argocd/csoc-addons/crds/ack-route53
  sync_wave: "-30"

- controller: ack-s3
  path: argocd/csoc-addons/crds/ack-s3
  sync_wave: "-30"

- controller: ack-secretsmanager
  path: argocd/csoc-addons/crds/ack-secretsmanager
  sync_wave: "-30"

- controller: ack-sns
  path: argocd/csoc-addons/crds/ack-sns
  sync_wave: "-30"

- controller: ack-sqs
  path: argocd/csoc-addons/crds/ack-sqs
  sync_wave: "-30"

- controller: ack-wafv2
  path: argocd/csoc-addons/crds/ack-wafv2
  sync_wave: "-30"

- controller: external-secrets
  path: argocd/csoc-addons/crds/external-secrets
  sync_wave: "-30"

- controller: metrics-server
  path: argocd/csoc-addons/crds/metrics-server
  sync_wave: "-30"

- controller: kube-state-metrics
  path: argocd/csoc-addons/crds/kube-state-metrics
  sync_wave: "-30"
